"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { Activity, ArrowUpRight, Check, Code2, Copy, Download, Globe, MousePointer2, Plus, RefreshCw, Settings2, ShieldCheck, Trash2, UserRound } from "lucide-react";
import WorkspaceNav from "@/components/workspace-nav";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Switch } from "@/components/ui/switch";
import { defaultWidgetCourses, embedCode, type WidgetSite } from "@/lib/widget-shared";
import type { SiteNavigation } from "@/lib/site-domains";

type Visitor={id:string;consent_at:number;last_seen:number;name:string|null;phone:string|null;email:string|null;event_count:number;enquiries:number};
type Event={id:string;type:string;path:string;properties:string;occurred_at:number;session_id:string};
type Submission={id:string;visitor_id:string|null;course:string;contact_consent_at:number;whatsapp_consent_at:number|null;created_at:number;name:string|null;phone:string|null;email:string|null};
type Directory={owner:boolean;clients:{id:string;name:string;is_demo:number}[];sites:(WidgetSite&{client_name:string})[]};
type Report={site:WidgetSite;owner:boolean;days:number;summary:{visitors:number;sessions:number;events:number;pageViews:number;activeSeconds:number};conversions:{enquiries:number;linkedVisitors:number};visitors:Visitor[];hasMore:boolean;pages:{path:string;views:number}[];courses:{course:string;visitors:number;signals:number}[];submissions:Submission[];journey:Event[];sessions:{started_at:number;last_seen:number;attribution:string;device:string}[];selectedVisitor:string|null;generatedAt:number};
type ActionResult={id?:string;ok?:boolean;error?:string};
function Choice({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];disabled?:boolean}){return <Select value={value} onValueChange={v=>v&&onChange(v)} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
const time=(n:number)=>new Date(n).toLocaleString("en-IN",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});
const pretty=(s:string)=>s.replaceAll("_"," ");
function describe(e:Event){const p=JSON.parse(e.properties) as Record<string,string|number>;if(e.type==="active_time")return `${p.seconds} active seconds`;if(e.type==="scroll"||e.type==="video_progress")return `${p.percent}%${p.video?` · ${p.video}`:""}`;if(e.type==="performance")return `${p.loadMs} ms page load`;return p.course||p.action||p.form||"";}

export default function TrackingDashboard({navigation}:{navigation:SiteNavigation}){
  const [directory,setDirectory]=useState<Directory>({owner:false,clients:[],sites:[]}),[site,setSite]=useState(""),[days,setDays]=useState("30"),[page,setPage]=useState(0),[visitor,setVisitor]=useState("");
  const [data,setData]=useState<Report|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState("activity"),[modal,setModal]=useState<"create"|"configure"|null>(null),[forget,setForget]=useState(false),[enabled,setEnabled]=useState(true);
  const [formClient,setFormClient]=useState(""),[formCourses,setFormCourses]=useState(defaultWidgetCourses.map(c=>c.id));
  const seq=useRef(0),downloadController=useRef<AbortController|null>(null);
  const loadDirectory=useCallback(async()=>{const r=await fetch("/api/tracking",{cache:"no-store"});const j=await r.json() as Directory & {error?:string};if(!r.ok)throw Error(j.error);setDirectory(j as Directory);return j as Directory;},[]);
  useEffect(()=>{let cancelled=false;void loadDirectory().then(d=>{if(!cancelled)setSite(d.sites[0]?.id||"");}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;downloadController.current?.abort();};},[loadDirectory]);
  const load=useCallback(async()=>{
    if(!site)return;const n=++seq.current;setLoading(true);
    try{const r=await fetch(`/api/tracking?site=${site}&days=${days}&page=${page}${visitor?`&visitor=${visitor}`:""}`,{cache:"no-store"});const j=await r.json() as Report & {error?:string};if(!r.ok)throw Error(j.error);if(seq.current===n){setData(j);setError("");}}
    catch(e){if(seq.current===n)setError(e instanceof Error?e.message:"Unable to load tracking.");}finally{if(seq.current===n)setLoading(false);}
  },[site,days,page,visitor]);
  useEffect(()=>{void load();return()=>{seq.current++;};},[load]);
  useEffect(()=>{if(!site)return;const timer=setInterval(()=>{if(document.visibilityState==="visible"&&!busy)void load();},30000);return()=>clearInterval(timer);},[site,busy,load]);
  async function act(payload:Record<string,unknown>,success:string):Promise<ActionResult|null>{
    if(busy)return null;setBusy(true);setError("");setNotice("");
    try{const r=await fetch("/api/tracking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json() as ActionResult;if(!r.ok)throw Error(j.error);setNotice(success);await loadDirectory();return j;}
    catch(e){setError(e instanceof Error?e.message:"Unable to save.");return null;}finally{setBusy(false);}
  }
  async function demo(){const r=await act({action:"demo"},"Dummy coaching website ready. Open it to generate consented activity.");if(r?.id){setSite(r.id);setVisitor("");setPage(0);setTab("install");if(r.id===site)await load();}}
  function showSetup(kind:"create"|"configure") {setFormClient(directory.clients[0]?.id||"");setEnabled(data?.site.enabled===1);setFormCourses(kind==="configure"&&data?JSON.parse(data.site.courses).map((c:{id:typeof defaultWidgetCourses[number]["id"]})=>c.id):defaultWidgetCourses.map(c=>c.id));setModal(kind);setError("");}
  async function save(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const f=new FormData(e.currentTarget),payload={action:modal==="create"?"create":"configure",...(modal==="create"?{client:formClient}:{site,enabled}),name:f.get("name"),origins:String(f.get("origins")).split(/[\n,]/).map(s=>s.trim()).filter(Boolean),privacyUrl:f.get("privacy"),color:f.get("color"),retentionDays:Number(f.get("retention")),courses:defaultWidgetCourses.filter(c=>formCourses.includes(c.id)).map(c=>({id:c.id,label:String(f.get(`course-${c.id}`)||c.label)}))};
    const r=await act(payload,"Widget settings saved.");if(r){setModal(null);if(r.id){setSite(r.id);setPage(0);setVisitor("");setTab("install");}else await load();}
  }
  async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice("Embed code copied.");}catch{setNotice("Select the embed code below to copy it.");}}
  async function exportData(){
    setBusy(true);setError("");const controller=new AbortController();downloadController.current=controller;
    try{
      let cursor:string|null=null;const events:unknown[]=[];let metadata:Record<string,unknown>={};
      do{const r:Response=await fetch(`/api/tracking?site=${site}&days=${days}&export=events${visitor?`&visitor=${visitor}`:""}${cursor?`&after=${encodeURIComponent(cursor)}`:""}`,{cache:"no-store",signal:controller.signal});const j:Record<string,unknown>&{events:unknown[];nextCursor:string|null;error?:string}=await r.json() as Record<string,unknown>&{events:unknown[];nextCursor:string|null;error?:string};if(!r.ok)throw Error(j.error);events.push(...j.events);const {events:_,nextCursor,...rest}=j;metadata=rest;cursor=nextCursor;setNotice(`Preparing ${events.length.toLocaleString()} events…`);if(events.length>=20000&&cursor)throw Error("More than 20,000 events in this selection. Choose 7 days or one visitor, or use the paginated export API.");}while(cursor);
      const blob=new Blob([JSON.stringify({...metadata,exportedAt:new Date().toISOString(),events},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`orbitflow-events-${site.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`${events.length.toLocaleString()} events exported. Contact details are excluded.`);
    }catch(e){setError(e instanceof Error?e.message:"Export failed.");}finally{setBusy(false);downloadController.current=null;}
  }
  const selected=data?.visitors.find(v=>v.id===visitor),snippet=embedCode(site),metrics=data?.summary,courseMax=Math.max(1,...(data?.courses||[]).map(c=>c.visitors||0)),pageMax=Math.max(1,...(data?.pages||[]).map(p=>p.views||0));
  return <main className="wt-page">
    <WorkspaceNav active="tracking" owner={directory.owner} {...navigation}/>
    <div className="wt-heading"><div><p className="wt-eyebrow">ORBITFLOW / WEBSITE INTELLIGENCE</p><h1>Website intelligence.</h1><p>See what visitors explore, where interest grows and who asks to connect.</p></div><div className="wt-actions">{directory.owner&&<><Button variant="outline" disabled={busy} onClick={()=>void demo()}>Open dummy website <ArrowUpRight size={16}/></Button><Button disabled={busy||!directory.clients.length} onClick={()=>showSetup("create")}><Plus size={17}/>Add website</Button></>}</div></div>
    {error&&<div role="alert" className="wt-error">{error}<Button size="sm" variant="outline" onClick={()=>void(site?load():loadDirectory())}>Retry</Button></div>}
    {notice&&<p className="wt-notice" role="status"><Check size={16}/>{notice}</p>}
    {directory.sites.length>0&&<div className="wt-toolbar"><Choice label="Website" value={site} onChange={v=>{setSite(v);setData(null);setVisitor("");setPage(0);setNotice("");}} options={directory.sites.map(s=>({value:s.id,label:s.name}))} disabled={busy}/><Choice label="Report period" value={days} onChange={v=>{setDays(v);setPage(0);}} options={[{value:"7",label:"Last 7 days"},{value:"30",label:"Last 30 days"},{value:"90",label:"Last 90 days"}]} disabled={busy}/><span className="wt-updated">{loading?"Refreshing…":data?`Updated ${time(data.generatedAt)}`:""}</span><Button variant="outline" size="icon" aria-label="Refresh tracking" disabled={busy||loading} onClick={()=>void load()}><RefreshCw size={16}/></Button></div>}
    {!data?<section className="wt-empty"><Code2 size={38}/><h2>{loading?"Opening website tracking…":"Your next enquiry starts here."}</h2><p>{directory.owner?"Create a dummy coaching website to try the complete flow, or add a website to an existing coaching workspace.":"Your assigned website activity will appear here. Ask the studio owner to enable your workspace."}</p>{directory.owner&&!loading&&<Button disabled={busy} onClick={()=>void demo()}>Create dummy website</Button>}</section>:<>
      <section className="wt-metrics" aria-label="Consented website activity">{[{label:"Consented visitors",value:metrics?.visitors,Icon:UserRound},{label:"Page views",value:metrics?.pageViews,Icon:Globe},{label:"Active minutes",value:Math.round((metrics?.activeSeconds||0)/60),Icon:Activity},{label:"Enquiries received",value:data.conversions.enquiries,Icon:MousePointer2}].map((m,i)=><div className={i===3?"wt-highlight":""} key={m.label}><div><span>{m.label}</span><m.Icon size={18}/></div><strong>{(m.value||0).toLocaleString()}</strong><small>{i===3?`${data.conversions.linkedVisitors} visitors linked with permission`:i===2?"Visible tab · recent interaction":i===1?`${metrics?.sessions||0} consented sessions`:"Analytics opt-in only"}</small></div>)}</section>
      <Tabs value={tab} onValueChange={setTab}><div className="wt-tabbar"><TabsList aria-label="Tracking sections"><TabsTrigger value="activity">Visitor journeys</TabsTrigger><TabsTrigger value="leads">Enquiries</TabsTrigger><TabsTrigger value="install">Install & settings</TabsTrigger></TabsList><Button size="sm" variant="outline" disabled={busy} onClick={()=>void exportData()}><Download size={15}/>Export for AI</Button></div>
        <TabsContent value="activity"><div className="wt-workbench"><section className="wt-visitors"><div className="wt-panel-head"><h2>Visitors</h2><span>{metrics?.events||0} events</span></div>{visitor&&<Button variant="ghost" size="sm" onClick={()=>setVisitor("")}>Clear selection</Button>}<div className="wt-visitor-list">{data.visitors.length?data.visitors.map(v=><button key={v.id} className={`wt-visitor ${visitor===v.id?"selected":""}`} disabled={busy} onClick={()=>setVisitor(v.id)}><span className="wt-avatar"><UserRound size={18}/></span><span><strong>{v.name||`Visitor ${v.id.slice(0,6)}`}</strong><small>{v.event_count} events · {time(v.last_seen)}</small></span>{v.enquiries>0&&<span className="wt-tag">Enquiry</span>}</button>):<div className="wt-panel-empty"><Activity size={24}/><p>No consented activity yet.</p><span>Install the widget, allow analytics, then explore the demo.</span></div>}</div></section>
          <section className="wt-journey"><div className="wt-panel-head"><div><h2>{selected?.name||visitor?selected?.name||`Visitor ${visitor.slice(0,6)}`:"Choose a visitor"}</h2><p>{selected?.phone||"Explore the path from course interest to enquiry."}</p></div>{visitor&&directory.owner&&<Button size="icon" variant="outline" aria-label="Delete this visitor's activity" disabled={busy} onClick={()=>setForget(true)}><Trash2 size={16}/></Button>}</div>
            {visitor&&data.sessions.length>0&&<div className="wt-session"><ShieldCheck size={18}/><div><strong>Analytics consent recorded</strong><span>{selected?time(selected.consent_at):"Consented visitor"} · {data.sessions[0].device}</span><span>{Object.entries(JSON.parse(data.sessions[0].attribution)).map(([k,v])=>`${k}: ${v}`).join(" · ")||"Direct visit / attribution not supplied"}</span></div></div>}
            {visitor?<ol className="wt-timeline">{data.journey.length?data.journey.map(e=><li key={e.id}><span className="wt-event-dot"/><div><div className="wt-event-heading"><strong>{pretty(e.type)}</strong><time>{time(e.occurred_at)}</time></div><code>{e.path}</code>{describe(e)&&<p>{describe(e)}</p>}</div></li>):<li className="wt-panel-empty"><p>No events in this date range.</p></li>}</ol>:<div className="wt-panel-empty wt-timeline-empty"><MousePointer2 size={32}/><h3>A journey, with context.</h3><p>Choose a visitor to see pages, course views, clicks, active time and form activity in sequence.</p></div>}{visitor&&<p className="wt-footnote">Latest 100 events, newest first. Export includes the full selected range.</p>}
          </section></div>
          <div className="wt-insights"><section><h2>Pages drawing attention</h2>{data.pages.length?data.pages.map(p=><div className="wt-bar" key={p.path}><div><code>{p.path}</code><span>{p.views} views</span></div><progress max={pageMax} value={p.views}/></div>):<p>Page views appear after visitors allow analytics.</p>}</section><section><h2>Course interest</h2>{data.courses.length?data.courses.map(c=><div className="wt-bar" key={c.course}><div><span>{defaultWidgetCourses.find(x=>x.id===c.course)?.label||c.course}</span><span>{c.visitors} {c.visitors===1?"visitor":"visitors"} · {c.signals} signals</span></div><progress max={courseMax} value={c.visitors}/></div>):<p>Add course tags to your website to measure course visibility.</p>}<p className="wt-footnote">Visitors are distinct consented browser identifiers, not verified people. One person can appear again on another browser or after clearing storage. Signals count course-interest events, including repeats.</p></section></div>
        </TabsContent>
        <TabsContent value="leads"><section className="wt-enquiries"><div className="wt-panel-head"><div><h2>Enquiries from this widget</h2><p>Submitted contact details. Callback and WhatsApp permissions are recorded separately.</p></div><a href="/coaching">Open admissions <ArrowUpRight size={15}/></a></div><Table><TableHeader><TableRow><TableHead>Contact</TableHead><TableHead>Course</TableHead><TableHead>Permissions</TableHead><TableHead>Received</TableHead><TableHead>Journey</TableHead></TableRow></TableHeader><TableBody>{data.submissions.map(s=><TableRow key={s.id}><TableCell><strong>{s.name||"Contact deleted"}</strong><span>{s.phone}</span><span>{s.email}</span></TableCell><TableCell>{defaultWidgetCourses.find(c=>c.id===s.course)?.label||s.course}</TableCell><TableCell><span>Callback requested</span><span>{s.whatsapp_consent_at?"WhatsApp opted in":"No WhatsApp opt-in"}</span></TableCell><TableCell>{time(s.created_at)}</TableCell><TableCell>{s.visitor_id?<Button size="sm" variant="outline" onClick={()=>{setVisitor(s.visitor_id!);setTab("activity");}}>View activity</Button>:<span>No analytics link</span>}</TableCell></TableRow>)}</TableBody></Table>{!data.submissions.length&&<div className="wt-panel-empty"><p>No enquiries yet. A successful widget submission appears here and in Admissions.</p></div>}</section></TabsContent>
        <TabsContent value="install"><div className="wt-install-grid"><section className="wt-install"><div className="wt-panel-head"><h2>One script. Your whole website.</h2><Code2 size={22}/></div><p>Add this before the closing <code>&lt;/body&gt;</code> tag in your website template. It loads on every page that uses that template.</p><pre tabIndex={0}>{snippet}</pre><div className="wt-actions"><Button variant="outline" onClick={()=>void copy(snippet)}><Copy size={15}/>Copy embed code</Button><a className="wt-link-button" href={`https://www.orbitflow.work/dummy-coaching?site=${site}`} target="_blank" rel="noreferrer">Open dummy website <ArrowUpRight size={15}/></a></div><p className="wt-footnote">The public site key can appear in HTML. Keep account and provider credentials on the server.</p><h3>Tag meaningful interactions</h3><pre tabIndex={0}>{`<section data-orbit-course="mern">…</section>\n<a data-orbit-action="book-demo" href="/demo">Book a demo</a>\n<form data-orbit-form="admissions">…</form>\n<video data-orbit-video="course-intro" …></video>`}</pre><p>Tagged forms record start and submit actions. Their field values stay on your website. Contact details enter OrbitFlow only through the widget enquiry form.</p><p className="wt-footnote">External form submissions are interaction signals, not proof that the host website saved an enquiry. A course view means at least 50% of the tagged block became visible.</p></section>
          <aside className="wt-configuration"><div className="wt-panel-head"><h2>Website settings</h2>{directory.owner&&<Button variant="outline" size="icon" aria-label="Edit website settings" onClick={()=>showSetup("configure")}><Settings2 size={17}/></Button>}</div><dl><div><dt>Collection</dt><dd>{data.site.enabled?"Enabled · consent required":"Paused"}</dd></div><div><dt>Coaching workspace</dt><dd>{directory.sites.find(s=>s.id===site)?.client_name}</dd></div><div><dt>Allowed website origins</dt><dd>{(JSON.parse(data.site.origins) as string[]).map(o=><code key={o}>{o}</code>)}</dd></div><div><dt>Activity retention</dt><dd>{data.site.retention_days} days</dd></div><div><dt>Privacy notice</dt><dd><a href={data.site.privacy_url} target="_blank" rel="noreferrer">Open privacy page <ArrowUpRight size={14}/></a></dd></div></dl><div className="wt-privacy-note"><ShieldCheck size={22}/><h3>Permission before collection</h3><p>Visitors can enquire without analytics. Withdrawal stops tracking and removes their activity history. Submitted enquiries are retained for the requested callback.</p></div>{directory.owner&&<Button variant="outline" disabled={busy} onClick={async()=>{const r=await act({action:"purge",site},"Expired activity cleanup completed in a bounded batch.");if(r)await load();}}>Clean up expired activity</Button>}<p className="wt-footnote">Expired events leave reports immediately. Physical cleanup runs on widget session start, on the configured background runner, or with this button. No external AI analysis is enabled yet.</p></aside></div></TabsContent>
      </Tabs>
      {tab!=="install"&&<div className="wt-pagination"><Button variant="outline" size="sm" disabled={busy||page===0} onClick={()=>{setPage(page-1);setVisitor("");}}>Previous</Button><span>Page {page+1}</span><Button variant="outline" size="sm" disabled={busy||!data.hasMore} onClick={()=>{setPage(page+1);setVisitor("");}}>Next</Button></div>}
      <footer className="wt-footer"><span>OrbitFlow · Website intelligence</span><span>Consent-based activity, not a count of every visitor. Self-reported contact details.</span></footer>
    </>}
    <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal(null);}}><DialogContent className="wt-dialog"><DialogHeader><DialogTitle>{modal==="create"?"Connect a coaching website":"Widget settings"}</DialogTitle><DialogDescription>Use only website origins the institute has authorized. The widget uses this institute name in its consent notice.</DialogDescription></DialogHeader><form onSubmit={save}>{error&&<p role="alert" className="wt-error">{error}</p>}{modal==="create"&&<div className="wt-field"><Label>Coaching workspace</Label><Choice label="Coaching workspace" value={formClient} onChange={setFormClient} options={directory.clients.map(c=>({value:c.id,label:c.name}))}/></div>}<div className="wt-field"><Label htmlFor="site-name">Institute / widget name</Label><Input id="site-name" name="name" required minLength={2} maxLength={100} defaultValue={modal==="configure"?data?.site.name:""}/></div><div className="wt-field"><Label htmlFor="site-origins">Allowed HTTPS origins (one per line)</Label><Textarea id="site-origins" name="origins" required rows={3} placeholder="https://www.coaching.example" defaultValue={modal==="configure"?(JSON.parse(data?.site.origins||"[]") as string[]).join("\n"):""}/><small>Include www and the root domain separately when both serve pages. Use no trailing slash. For the built-in demo also allow https://www.orbitflow.work.</small></div><div className="wt-field"><Label htmlFor="site-privacy">Institute privacy page</Label><Input id="site-privacy" name="privacy" type="url" required defaultValue={modal==="configure"?data?.site.privacy_url:""}/></div><div className="wt-form-grid"><div className="wt-field"><Label htmlFor="site-color">Accent color</Label><Input id="site-color" name="color" type="color" defaultValue={modal==="configure"?data?.site.color:"#fa783c"}/></div><div className="wt-field"><Label htmlFor="site-retention">Activity retention (days)</Label><Input id="site-retention" name="retention" type="number" min={7} max={180} required defaultValue={modal==="configure"?data?.site.retention_days:90}/></div></div><fieldset><legend>Courses shown in the widget</legend>{defaultWidgetCourses.map(c=><div className="wt-course-setting" key={c.id}><Switch checked={formCourses.includes(c.id)} onCheckedChange={on=>setFormCourses(prev=>on?[...prev,c.id]:prev.filter(x=>x!==c.id))} aria-label={`Show ${c.label}`}/><Input name={`course-${c.id}`} aria-label={`${c.id} display name`} maxLength={80} defaultValue={modal==="configure"?(JSON.parse(data?.site.courses||"[]") as {id:string;label:string}[]).find(x=>x.id===c.id)?.label||c.label:c.label}/></div>)}</fieldset>{modal==="configure"&&<div className="wt-switch"><Switch id="widget-enabled" checked={enabled} onCheckedChange={setEnabled}/><Label htmlFor="widget-enabled">Enable enquiries and consented tracking</Label></div>}<Button type="submit" disabled={busy||!formCourses.length||modal==="create"&&!formClient}>{busy?"Saving…":"Save widget"}</Button></form></DialogContent></Dialog>
    <AlertDialog open={forget} onOpenChange={setForget}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this visitor’s activity?</AlertDialogTitle><AlertDialogDescription>Events and sessions will be deleted, the enquiry link removed, and this tracking identity blocked. Submitted contact enquiries remain in Admissions for their separately requested callback.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep activity</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{const r=await act({action:"forget",site,visitor},"Visitor activity deleted and tracking identity blocked.");if(r){setForget(false);setVisitor("");await load();}}}>Delete activity</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}
