import assert from 'node:assert/strict';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {build} from 'esbuild';

const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
function prepare(sql){let values=[];return{bind(...args){values=args;return this},async first(){return sqlite.prepare(sql).get(...values)||null},async all(){return{results:sqlite.prepare(sql).all(...values),success:true}},async run(){return{meta:{changes:sqlite.prepare(sql).run(...values).changes},success:true}}}}
const db={prepare,async batch(stmts){sqlite.exec('BEGIN');try{const rows=[];for(const s of stmts)rows.push(await s.all());sqlite.exec('COMMIT');return rows}catch(e){sqlite.exec('ROLLBACK');throw e}}};
globalThis.__coachingEnv={DB:db,ORBIT_ADMIN_EMAIL:'owner@example.test'};globalThis.__coachingHeaders=new Headers();
const built=await build({stdin:{contents:'export * as api from "./app/api/coaching/route.ts";export * as intake from "./app/api/coaching/intake/[client]/route.ts"; export * as webhooks from "./app/api/coaching/whatsapp/[client]/route.ts";export * as engine from "./lib/coaching.ts";export * as whatsapp from "./lib/coaching-whatsapp.ts";export * as gemini from "./lib/coaching-gemini.ts";export * as csv from "./lib/coaching-csv.ts";export * as core from "./lib/workflow-engine.ts";',resolveDir:new URL('..',import.meta.url).pathname},bundle:true,write:false,format:'esm',platform:'node',target:'node24',plugins:[{name:'platform',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},a=>({path:a.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.__coachingEnv;':a.path==='next/headers'?'export async function headers(){return globalThis.__coachingHeaders}':'export function redirect(){throw Error("Unexpected API redirect")}',loader:'js'}))}}]});
const {api,intake,engine,whatsapp,webhooks,gemini,csv,core}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const auth=(email='owner@example.test',id='owner')=>globalThis.__coachingHeaders=new Headers({'oai-authenticated-user-id':id,'oai-authenticated-user-email':email});
const post=(payload,origin='https://orbit.example')=>api.POST(new Request('https://orbit.example/api/coaching',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(payload)}));
const get=(client,lead)=>api.GET(new Request(`https://orbit.example/api/coaching${client?'?client='+client:''}${lead?'&lead='+lead:''}`));
function reset(){for(const t of ['voice_attempts','voice_calls','voice_settings','voice_suppression','coaching_messages','coaching_bookings','coaching_slots','coaching_students','coaching_settings','operation_alerts','workflow_jobs','leads','workflows','memberships','clients','rate_limits'])sqlite.exec(`DELETE FROM ${t}`);globalThis.__coachingEnv.ORBIT_COACHING_CONNECTORS_JSON='{}';globalThis.__coachingEnv.ORBIT_CONNECTORS_JSON='{}';globalThis.__coachingEnv.ORBIT_GEMINI_KEY='';auth();}
function client(demo=1){const id=crypto.randomUUID();sqlite.prepare('INSERT INTO clients(id,name,intake_key_hash,created_at) VALUES(?,?,?,?)').run(id,'Coaching test','unused',Date.now());sqlite.prepare('INSERT INTO coaching_settings(client_id,is_demo,created_at) VALUES(?,?,?)').run(id,demo,Date.now());return id;}
const input=(more={})=>engine.coachingLeadInput.parse({name:'Test student',phone:'+919876543210',course:'mern',source:'Test form',consentAt:Date.now()-1000,consentEvidence:'Test form explicit WhatsApp opt-in',...more});
const lead=(c,more={})=>engine.captureLead(c,input(more));
function slot(c,more={}){const row={id:crypto.randomUUID(),course:'mern',centre:'Bhawarkua',startsAt:Date.now()+86400000,capacity:1,...more};sqlite.prepare('INSERT INTO coaching_slots(id,client_id,course,centre,starts_at,capacity) VALUES(?,?,?,?,?,?)').run(row.id,c,row.course,row.centre,row.startsAt,row.capacity);return row;}
function config(c){const cfg={token:'test-token',phoneId:'123456789',version:'v25.0',appSecret:'test-app-secret-123456',verifyToken:'test-verify-token-123456789012',language:'en',welcomeTemplate:'test_welcome',bookingTemplate:'test_booking',reminderTemplate:'test_reminder',allowedRecipients:['+919876543210','+919876543211']};globalThis.__coachingEnv.ORBIT_COACHING_CONNECTORS_JSON=JSON.stringify({[c]:cfg});return cfg;}
async function signed(c,body,secret,signature=true){const raw=JSON.stringify(body),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(raw))).toString('hex');return webhooks.POST(new Request(`https://orbit.example/api/coaching/whatsapp/${c}`,{method:'POST',headers:{'content-type':'application/json',...(signature?{'x-hub-signature-256':'sha256='+sig}:{})},body:raw}),{params:Promise.resolve({client:c})});}
const payload=(phoneId,extra)=>({object:'whatsapp_business_account',entry:[{changes:[{value:{metadata:{phone_number_id:phoneId},...extra}}]}]});

test('coaching admissions with real SQLite and isolated providers',async t=>{
 await t.test('anonymous, cross-origin and cross-client reads/writes are denied',async()=>{reset();globalThis.__coachingHeaders=new Headers();assert.equal((await get()).status,401);auth();assert.equal((await post({action:'createDemo'},'https://untrusted.example')).status,403);const a=client(),b=client();sqlite.prepare('INSERT INTO memberships(id,client_id,email,created_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),a,'member@example.test',Date.now());const l=await lead(b);auth('member@example.test','member');assert.equal((await get(a)).status,200);assert.equal((await get(b)).status,403);assert.equal((await post({action:'optOut',client:a,id:l.id})).status,404);assert.equal((await post({action:'createDemo'})).status,403);});
 await t.test('phone-only leads and normalized duplicate imports send one welcome',async()=>{reset();const c=client();const one=await lead(c,{phone:'98765 43210'}),two=await lead(c,{phone:'+91 98765-43210'});assert.equal(one.id,two.id);assert.equal(two.duplicate,true);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM leads').get().n,1);assert.equal(sqlite.prepare('SELECT email FROM leads').get().email,'');assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM coaching_messages').get().n,1);assert.equal(core.leadInput.safeParse({externalRef:'phone-only',name:'Phone lead',phone:'+919876543210'}).success,true);assert.equal(core.leadInput.safeParse({externalRef:'neither',name:'No contact'}).success,false);});
 await t.test('import validation is performed before writes and consent is never inferred',async()=>{reset();const c=client();const r=await post({action:'import',client:c,leads:[input(),{...input(),phone:'bad'}]});assert.equal(r.status,400);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM leads').get().n,0);await lead(c,{consentAt:null,consentEvidence:''});assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM coaching_messages').get().n,0);assert.equal(engine.coachingLeadInput.safeParse(input({consentAt:null,consentEvidence:''})).success,true);assert.equal(engine.coachingLeadInput.safeParse({...input(),consentAt:Date.now()+3600000}).success,false);});
 await t.test('idempotent demo creation seeds fictional contacts and cannot send externally',async()=>{reset();const a=await engine.createDemo(),b=await engine.createDemo();assert.equal(a,b);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM leads').get().n,3);config(a);sqlite.prepare("UPDATE coaching_messages SET status='queued',send_at=0").run();let calls=0;await whatsapp.processOutgoing(a,async()=>{calls++;throw Error('never')});assert.equal(calls,0);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM coaching_messages WHERE status='simulated'").get().n,2);});
 await t.test('student chat books a slot, captures preference and deduplicates inbound events',async()=>{reset();const c=client(),l=await lead(c),a=slot(c);await engine.receiveMessage(c,l.id,'in-1','Online');await engine.receiveMessage(c,l.id,'in-1','Online');await engine.processIncoming(c);await engine.receiveMessage(c,l.id,'in-2','DEMO');await engine.processIncoming(c);await engine.receiveMessage(c,l.id,'in-3','BOOK 1');await engine.processIncoming(c);const s=await engine.student(c,l.id);assert.equal(s.learning_mode,'Online');assert.equal(s.stage,'booked');assert.equal(sqlite.prepare('SELECT slot_id FROM coaching_bookings').get().slot_id,a.id);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM coaching_messages WHERE direction='inbound'").get().n,3);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM coaching_messages WHERE kind='reminder' AND status='queued'").get().n,1);});
 await t.test('capacity is atomic and a booking cannot use another client slot',async()=>{reset();const c=client(),other=client(),a=await lead(c),b=await lead(c,{phone:'+919876543211'}),s=slot(c),foreign=slot(other);const results=await Promise.allSettled([engine.bookSlot(c,a.id,s.id),engine.bookSlot(c,b.id,s.id)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM coaching_bookings WHERE status='confirmed'").get().n,1);await assert.rejects(engine.bookSlot(c,a.id,foreign.id),e=>e.status===409);});
 await t.test('rescheduling preserves capacity and cancels obsolete reminders; repeated booking does not duplicate',async()=>{reset();const c=client(),l=await lead(c),a=slot(c),b=slot(c);const initial=await engine.bookSlot(c,l.id,a.id);await engine.bookSlot(c,l.id,a.id);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM coaching_messages WHERE kind='booking'").get().n,1);const changed=await engine.bookSlot(c,l.id,b.id);assert.notEqual(changed.id,initial.id);assert.equal(sqlite.prepare("SELECT status FROM coaching_messages WHERE id=?").get('reminder:'+initial.id).status,'cancelled');await engine.cancelBooking(c,l.id);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM coaching_messages WHERE status='queued'").get().n,0);});
 await t.test('STOP suppresses pending sends immediately, even before inbound processing',async()=>{reset();const c=client(0),l=await lead(c);config(c);await engine.receiveMessage(c,l.id,'stop-now','STOP');let calls=0;await whatsapp.processOutgoing(c,async()=>{calls++;return Response.json({messages:[{id:'never'}]})});assert.equal(calls,0);assert.ok((await engine.student(c,l.id)).opted_out_at);await engine.processIncoming(c);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM coaching_messages WHERE direction='outbound' AND status NOT IN ('cancelled','blocked')").get().n,0);});
 await t.test('unverified fees transfer to a counsellor and pause the assistant',async()=>{reset();const c=client(),l=await lead(c);await engine.receiveMessage(c,l.id,'fee-question','Fees?');await engine.processIncoming(c);assert.equal((await engine.student(c,l.id)).handoff,1);const count=sqlite.prepare("SELECT COUNT(*) n FROM coaching_messages WHERE direction='outbound'").get().n;await engine.receiveMessage(c,l.id,'later','DEMO');await engine.processIncoming(c);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM coaching_messages WHERE direction='outbound'").get().n,count);});
 await t.test('only signed, matching-phone events can enter a live workspace',async()=>{reset();const c=client(0),cfg=config(c);const body=payload(cfg.phoneId,{messages:[{id:'wamid.in1',from:'919876543210',timestamp:String(Math.floor(Date.now()/1000)),type:'text',text:{body:'Hi'}}]});assert.equal((await signed(c,body,cfg.appSecret,false)).status,403);assert.equal((await signed(c,body,'incorrect-app-secret')).status,403);assert.equal((await signed(c,payload('different-phone',{}),cfg.appSecret)).status,403);assert.equal((await signed(c,body,cfg.appSecret)).status,200);assert.equal((await signed(c,body,cfg.appSecret)).status,200);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM leads').get().n,1);assert.equal(sqlite.prepare('SELECT consent_at FROM leads').get().consent_at,null);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM coaching_messages').get().n,1);const l=sqlite.prepare('SELECT id FROM leads').get();assert.equal((await post({action:'message',client:c,id:l.id,asStudent:true,text:'forged',requestId:crypto.randomUUID()})).status,403);});
 await t.test('service window, allowlist and opt-in are checked before external sends',async()=>{reset();const c=client(0),l=await lead(c,{consentAt:null,consentEvidence:''});config(c);await engine.enqueue(c,l.id,'outside-window','text','Hello');let calls=0;await whatsapp.processOutgoing(c,async()=>{calls++;return Response.json({messages:[{id:'unexpected'}]})});assert.equal(calls,0);assert.equal(sqlite.prepare('SELECT error_code FROM coaching_messages').get().error_code,'customer_service_window_closed');const other=await lead(c,{phone:'+919876543299'});await whatsapp.processOutgoing(c,async()=>{calls++;return Response.json({messages:[{id:'unexpected'}]})});assert.equal(calls,0);assert.equal(sqlite.prepare('SELECT status FROM coaching_messages WHERE lead_id=?').get(other.id).status,'blocked');});
 await t.test('provider acceptance and monotonic delivered/read states are distinct',async()=>{reset();const c=client(0),cfg=config(c);await lead(c);await whatsapp.processOutgoing(c,async(url,options)=>{assert.ok(url.startsWith('https://graph.facebook.com/'));const body=JSON.parse(options.body);assert.equal(body.template.components[0].parameters.length,2);return Response.json({messages:[{id:'wamid.out1'}]})});assert.equal(sqlite.prepare('SELECT status FROM coaching_messages').get().status,'accepted');for(const status of ['read','delivered','sent','failed'])assert.equal((await signed(c,payload(cfg.phoneId,{statuses:[{id:'wamid.out1',status}]}),cfg.appSecret)).status,200);assert.equal(sqlite.prepare('SELECT status FROM coaching_messages').get().status,'read');});
 await t.test('ambiguous sends require review and concurrent runners do not duplicate',async()=>{reset();const c=client(0);config(c);await lead(c);let calls=0;const transport=async()=>{calls++;await new Promise(r=>setTimeout(r,5));throw Error('timeout after provider accepted')};await Promise.all([whatsapp.processOutgoing(c,transport),whatsapp.processOutgoing(c,transport)]);assert.equal(calls,1);assert.equal(sqlite.prepare('SELECT status FROM coaching_messages').get().status,'needs_review');await whatsapp.processOutgoing(c,transport);assert.equal(calls,1);});
 await t.test('CSV handles quotes, explicit ISO consent, row bounds and unknown headers',async()=>{reset();assert.equal(csv.parseCoachingCsv('name,phone,course\n"Last, First",+447700900001,mern')[0].name,'Last, First');assert.equal(csv.parseCoachingCsv('name,phone\nTest,+447700900001')[0].consentAt,null);assert.throws(()=>csv.parseCoachingCsv('name,phone,consent_at\nTest,+447700900001,2026-09-09T10:00:00'));assert.throws(()=>csv.parseCoachingCsv('name,phone,permission\nTest,+447700900001,yes'));});
 await t.test('Gemini accepts only bounded commands, redacts contacts and falls back on quota/errors',async()=>{reset();const c=client();globalThis.__coachingEnv.ORBIT_GEMINI_KEY='test-server-only';let body;const result=await gemini.understandWithGemini('I am interested in web UIs. Email me at demo@example.test or +919876543210',c,async(url,options)=>{body=options.body;assert.ok(url.startsWith('https://generativelanguage.googleapis.com/'));assert.equal(options.headers['x-goog-api-key'],'test-server-only');return Response.json({candidates:[{content:{parts:[{text:'{"command":"MERN"}'}]}}]})});assert.equal(result,'MERN');assert.ok(!body.includes('demo@example.test'));assert.ok(!body.includes('919876543210'));assert.equal(await gemini.understandWithGemini('unknown',c,async()=>new Response('{}',{status:429})),null);assert.equal(await gemini.understandWithGemini('unknown',c,async()=>Response.json({candidates:[{content:{parts:[{text:'{"command":"SEND_MONEY"}'}]}}]})),null);assert.equal(await gemini.understandWithGemini('unknown',c,async()=>{throw Error('timeout')}),null);});
 await t.test('website intake requires the workspace key and rejects revoked keys',async()=>{reset();const c=client(0),key='coaching-test-key-'+crypto.randomUUID(),hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key))).toString('hex');sqlite.prepare('UPDATE clients SET intake_key_hash=? WHERE id=?').run(hash,c);const request=token=>new Request('https://orbit.example/api/coaching/intake/'+c,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:JSON.stringify(input({consentAt:null,consentEvidence:''}))});assert.equal((await intake.POST(request('invalid'),{params:Promise.resolve({client:c})})).status,401);assert.equal((await intake.POST(request(key),{params:Promise.resolve({client:c})})).status,201);sqlite.prepare('UPDATE clients SET intake_key_hash=? WHERE id=?').run('rotated',c);assert.equal((await intake.POST(request(key),{params:Promise.resolve({client:c})})).status,401);});
 await t.test('signed callback reconciles an ambiguous send using its opaque reference',async()=>{reset();const c=client(0),cfg=config(c);await lead(c);await whatsapp.processOutgoing(c,async()=>{throw Error('lost result')});const m=sqlite.prepare('SELECT id,status FROM coaching_messages').get();assert.equal(m.status,'needs_review');const event=payload(cfg.phoneId,{statuses:[{id:'wamid.recovered',status:'delivered',biz_opaque_callback_data:m.id}]});assert.equal((await signed(c,event,cfg.appSecret)).status,200);assert.equal(sqlite.prepare('SELECT status FROM coaching_messages').get().status,'delivered');});
 await t.test('GET exposes no secrets and demo sends cannot be turned live through API',async()=>{reset();const c=await engine.createDemo();config(c);const r=await get(c);assert.equal(r.status,200);const raw=await r.text();assert.ok(!raw.includes('test-token'));assert.ok(!raw.includes('test-app-secret'));await post({action:'enableWorkspace',client:c});assert.equal((await engine.settings(c)).is_demo,1);});
});
