import assert from 'node:assert/strict';
import test from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, readdirSync } from 'node:fs';
import { build } from 'esbuild';

const sqlite=new DatabaseSync(':memory:');
sqlite.exec('PRAGMA foreign_keys = ON');
for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
function prepare(sql){let values=[];return {bind(...args){values=args;return this},async first(){return sqlite.prepare(sql).get(...values)||null},async all(){return {results:sqlite.prepare(sql).all(...values),success:true}},async run(){return {success:true,meta:{changes:sqlite.prepare(sql).run(...values).changes}}}};}
const db={prepare,async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.all());sqlite.exec('COMMIT');return results}catch(err){sqlite.exec('ROLLBACK');throw err}}};
globalThis.__opsEnv={DB:db,ORBIT_ADMIN_EMAIL:'owner@example.test'};
globalThis.__opsHeaders=new Headers();
const built=await build({stdin:{contents:'export * as routes from "./app/api/operations/route.ts"; export * as intake from "./app/api/intake/[client]/route.ts"; export * as runner from "./app/api/runner/route.ts"; export * as engine from "./lib/workflow-engine.ts";',resolveDir:new URL('..',import.meta.url).pathname},bundle:true,write:false,format:'esm',platform:'node',target:'node24',plugins:[{name:'ops-test-platform',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},args=>({path:args.path,namespace:'test-platform'}));b.onLoad({filter:/.*/,namespace:'test-platform'},args=>({contents:args.path==='cloudflare:workers'?'export const env=globalThis.__opsEnv;':args.path==='next/headers'?'export async function headers(){return globalThis.__opsHeaders;}':'export function redirect(){throw new Error("Unexpected API redirect");}',loader:'js'}))}}]});
const {routes,intake,runner,engine}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const auth=(email='owner@example.test',id='owner-id')=>{globalThis.__opsHeaders=new Headers({'oai-authenticated-user-email':email,'oai-authenticated-user-id':id})};
const post=(payload,extra={})=>routes.POST(new Request('https://orbit.example/api/operations',{method:'POST',headers:{'content-type':'application/json',origin:'https://orbit.example',...extra},body:JSON.stringify(payload)}));
const get=client=>routes.GET(new Request('https://orbit.example/api/operations'+(client?'?client='+client:'')));
const reset=()=>{for(const t of ['case_consent_events','case_studies','operation_alerts','workflow_jobs','leads','workflows','memberships','onboarding','monthly_reports','feature_requests','clients','rate_limits'])sqlite.exec(`DELETE FROM ${t}`);globalThis.__opsEnv.ORBIT_CONNECTORS_JSON='{}';globalThis.__opsEnv.ORBIT_RESEND_KEY='';globalThis.__opsEnv.ORBIT_EMAIL_FROM='';auth()};
async function create(email='client@example.test'){auth();const id=crypto.randomUUID();const response=await post({action:'createClient',requestId:id,name:'Test client',email});assert.equal(response.status,201);return {id,...await response.json()};}
const input=(overrides={})=>({externalRef:crypto.randomUUID(),name:'Test Contact',email:'contact@example.test',phone:'',brief:'A lead for our workflow pilot.',consentEvidence:'',consentAt:null,...overrides});
async function lead(client,overrides={}){const data=input(overrides);const r=await post({action:'addLead',client,lead:data});assert.equal(r.status,201);return {data,...await r.json()};}
function config(client){globalThis.__opsEnv.ORBIT_CONNECTORS_JSON=JSON.stringify({[client]:{hubspotToken:'provider-secret-test-only',alertEmail:'alerts@example.test',whatsapp:{token:'test-token',phoneId:'123456789',version:'v23.0',template:'pilot_welcome',language:'en'}}});globalThis.__opsEnv.ORBIT_RESEND_KEY='resend-test-only';globalThis.__opsEnv.ORBIT_EMAIL_FROM='ORBIT <alerts@example.test>'}

test('client operations: real handlers, real SQLite, isolated providers',async t=>{
 await t.test('anonymous and cross-site calls cannot create workspaces',async()=>{reset();globalThis.__opsHeaders=new Headers();assert.equal((await get()).status,401);assert.equal((await post({action:'createClient',requestId:crypto.randomUUID(),name:'Test client',email:'x@example.test'})).status,401);auth();assert.equal((await post({action:'createClient',requestId:crypto.randomUUID(),name:'Test client',email:'x@example.test'},{origin:'https://attacker.example'})).status,403);});
 await t.test('membership binds once to stable identity and enforces tenant boundaries',async()=>{reset();const a=await create(),b=await create('other@example.test');const l=await lead(b.id);auth('client@example.test','client-one');assert.equal((await get(a.id)).status,200);assert.equal((await get(b.id)).status,403);assert.equal((await post({action:'updateLead',client:a.id,id:l.id,status:'won',followUpAt:null,responded:true,optOut:false})).status,404);assert.equal(sqlite.prepare('SELECT status FROM leads WHERE id = ?').get(l.id).status,'new');auth('client@example.test','different-identity');assert.equal((await get(a.id)).status,403);auth('changed-address@example.test','client-one');assert.equal((await get(a.id)).status,200);auth();const member=sqlite.prepare('SELECT id FROM memberships WHERE client_id = ?').get(a.id);await post({action:'revokeMember',client:a.id,id:member.id});auth('client@example.test','client-one');assert.equal((await get(a.id)).status,403);});
 await t.test('client members cannot enable workflows or manage other memberships',async()=>{reset();const c=await create();auth('client@example.test','member');assert.equal((await post({action:'workflow',client:c.id,template:'crm.sync',enabled:true})).status,403);assert.equal((await post({action:'addMember',client:c.id,email:'intruder@example.test'})).status,403);});
 await t.test('lead intake is idempotent and queues each enabled template once',async()=>{reset();const c=await create();for(const template of ['crm.sync','email.alert'])await post({action:'workflow',client:c.id,template,enabled:true});const l=await lead(c.id);assert.equal((await post({action:'addLead',client:c.id,lead:l.data})).status,201);assert.equal((await post({action:'addLead',client:c.id,lead:{...l.data,name:'Changed Contact'}})).status,409);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM leads').get().n,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM workflow_jobs').get().n,2);assert.equal(sqlite.prepare('SELECT intake_key_hash FROM clients').get().intake_key_hash.includes(c.intakeKey),false);});
 await t.test('missing credentials block runs without issuing a network request or claiming success',async()=>{reset();const c=await create();await post({action:'workflow',client:c.id,template:'crm.sync',enabled:true});await lead(c.id);let calls=0;await engine.processJobs(c.id,async()=>{calls++;throw new Error('Must not send')});assert.equal(calls,0);assert.equal(sqlite.prepare("SELECT status FROM workflow_jobs WHERE action='crm.sync'").get().status,'blocked');assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM operation_alerts').get().n,2);});
 await t.test('transient CRM failure retries the same payload and counts one accepted operation',async()=>{reset();const c=await create();config(c.id);await post({action:'workflow',client:c.id,template:'crm.sync',enabled:true});await lead(c.id);await engine.processJobs(c.id,async()=>new Response('{}',{status:503}));const j=sqlite.prepare("SELECT * FROM workflow_jobs WHERE action='crm.sync'").get();assert.equal(j.status,'retry');assert.equal(j.attempts,1);assert.ok(j.next_at>Date.now());sqlite.prepare('UPDATE workflow_jobs SET next_at=0').run();let payload;await engine.processJobs(c.id,async(url,options)=>{assert.equal(url,'https://api.hubapi.com/crm/v3/objects/contacts/batch/upsert');payload=options.body;return Response.json({results:[{id:'crm-contact-1'}]})});assert.equal(payload,j.payload?JSON.stringify(JSON.parse(j.payload).body):'missing');const done=sqlite.prepare('SELECT * FROM workflow_jobs').get();assert.equal(done.status,'succeeded');assert.equal(done.attempts,2);assert.equal(done.provider_id,'crm-contact-1');const r=await engine.reportMetrics(c.id,new Date().toISOString().slice(0,7));assert.equal(r.usage[0].accepted,1);});
 await t.test('concurrent processors cannot send the same job twice',async()=>{reset();const c=await create();config(c.id);await post({action:'workflow',client:c.id,template:'crm.sync',enabled:true});await lead(c.id);let sends=0;const transport=async()=>{sends++;await new Promise(resolve=>setTimeout(resolve,10));return Response.json({results:[{id:'once'}]})};await Promise.all([engine.processJobs(c.id,transport),engine.processJobs(c.id,transport)]);assert.equal(sends,1);});
 await t.test('WhatsApp requires opt-in; an ambiguous send enters review and cannot be retried',async()=>{reset();const c=await create();config(c.id);const noConsent=await lead(c.id);assert.equal((await post({action:'sendWhatsApp',client:c.id,id:noConsent.id,confirm:true})).status,400);const l=await lead(c.id,{phone:'+919876543210',consentAt:Date.now()-1000,consentEvidence:'Explicit opt-in on form reference TEST-01'});await post({action:'sendWhatsApp',client:c.id,id:l.id,confirm:true});let whatsappCalls=0;await engine.processJobs(c.id,async(url)=>{if(url.includes('graph.facebook.com')){whatsappCalls++;throw new Error('timeout after submission')}return Response.json({id:'alert-email'})});const j=sqlite.prepare("SELECT * FROM workflow_jobs WHERE action='whatsapp.template'").get();assert.equal(j.status,'needs_review');assert.equal(whatsappCalls,1);assert.equal((await post({action:'retryJob',client:c.id,id:j.id})).status,409);await engine.processJobs(c.id,async()=>{throw new Error('must not re-send')});assert.equal(whatsappCalls,1);});
 await t.test('opt-out before processing prevents an already queued WhatsApp send',async()=>{reset();const c=await create();config(c.id);const l=await lead(c.id,{phone:'+919876543210',consentAt:Date.now()-1000,consentEvidence:'Client form opt-in TEST-02'});await post({action:'sendWhatsApp',client:c.id,id:l.id,confirm:true});await post({action:'updateLead',client:c.id,id:l.id,status:'new',followUpAt:null,responded:false,optOut:true});await engine.processJobs(c.id,async url=>{assert.ok(!url.includes('graph.facebook.com'));return Response.json({id:'alert-email'})});assert.equal(sqlite.prepare("SELECT status FROM workflow_jobs WHERE action='whatsapp.template'").get().status,'blocked');});
 await t.test('expired WhatsApp leases are reviewed instead of automatically resent',async()=>{reset();const c=await create();config(c.id);const l=await lead(c.id,{phone:'+919876543210',consentAt:Date.now()-1000,consentEvidence:'Consent form TEST-03'});await engine.queueJob(c.id,l.id,'whatsapp.template');sqlite.prepare("UPDATE workflow_jobs SET status='processing', lease_until=1, attempts=1").run();await engine.processJobs(c.id,async url=>{assert.ok(!url.includes('graph.facebook.com'));return Response.json({id:'error-alert'})});assert.equal(sqlite.prepare("SELECT status FROM workflow_jobs WHERE action='whatsapp.template'").get().status,'needs_review');});
 await t.test('email retries use a stable idempotency key and stop before provider retention expires',async()=>{reset();const c=await create();config(c.id);await post({action:'workflow',client:c.id,template:'email.alert',enabled:true});await lead(c.id);const keys=[];await engine.processJobs(c.id,async(url,options)=>{keys.push(options.headers['Idempotency-Key']);return new Response('{}',{status:503})});sqlite.prepare('UPDATE workflow_jobs SET next_at=0').run();await engine.processJobs(c.id,async(url,options)=>{keys.push(options.headers['Idempotency-Key']);return new Response('{}',{status:503})});assert.equal(keys[0],keys[1]);sqlite.prepare('UPDATE workflow_jobs SET next_at=0, created_at=?').run(Date.now()-24*3600000);await engine.processJobs(c.id,async()=>{assert.fail('old email must not be resent')});assert.equal(sqlite.prepare('SELECT status FROM workflow_jobs').get().status,'needs_review');});
 await t.test('response tracking records only the first human response and reports null for no samples',async()=>{reset();const c=await create();const l=await lead(c.id);let m=await engine.reportMetrics(c.id,new Date().toISOString().slice(0,7));assert.equal(m.average_response_minutes,null);sqlite.prepare('UPDATE leads SET created_at=? WHERE id=?').run(Date.now()-120000,l.id);await post({action:'updateLead',client:c.id,id:l.id,status:'contacted',followUpAt:null,responded:true,optOut:false});const first=sqlite.prepare('SELECT first_response_at FROM leads').get().first_response_at;await post({action:'updateLead',client:c.id,id:l.id,status:'won',followUpAt:null,responded:true,optOut:false});assert.equal(sqlite.prepare('SELECT first_response_at FROM leads').get().first_response_at,first);m=await engine.reportMetrics(c.id,new Date().toISOString().slice(0,7));assert.equal(m.won,1);assert.equal(m.responded,1);assert.ok(m.average_response_minutes>=2);});
 await t.test('case-study consent requires a client, exact version and reapproval after edits',async()=>{reset();const c=await create();const caseId=crypto.randomUUID();const draft={action:'caseDraft',client:c.id,id:caseId,title:'A measured pilot',text:'Actual pilot evidence will be recorded here with its measurement dates.',expectedHash:null};assert.equal((await post(draft)).status,200);let study=sqlite.prepare('SELECT * FROM case_studies').get();assert.equal((await post({action:'caseConsent',client:c.id,id:caseId,hash:study.content_hash,decision:'approve',confirm:true})).status,403);auth('client@example.test','member');assert.equal((await post({action:'caseConsent',client:c.id,id:caseId,hash:'a'.repeat(64),decision:'approve',confirm:true})).status,409);assert.equal((await post({action:'caseConsent',client:c.id,id:caseId,hash:study.content_hash,decision:'approve',confirm:true})).status,200);assert.equal(sqlite.prepare('SELECT status FROM case_studies').get().status,'approved');assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM case_consent_events').get().n,1);auth();assert.equal((await post({...draft,text:draft.text+' Updated methodology.',expectedHash:study.content_hash})).status,200);study=sqlite.prepare('SELECT * FROM case_studies').get();assert.equal(study.status,'draft');assert.equal(study.approved_hash,null);});
 await t.test('intake validates its workspace key; rotated keys cannot create leads',async()=>{reset();const c=await create();const incoming=(key)=>new Request('https://orbit.example/api/intake/'+c.id,{method:'POST',headers:{authorization:'Bearer '+key,'content-type':'application/json'},body:JSON.stringify(input())});assert.equal((await intake.POST(incoming('invalid'),{params:Promise.resolve({client:c.id})})).status,401);assert.equal((await intake.POST(incoming(c.intakeKey),{params:Promise.resolve({client:c.id})})).status,201);await post({action:'rotateKey',client:c.id});assert.equal((await intake.POST(incoming(c.intakeKey),{params:Promise.resolve({client:c.id})})).status,401);});
 await t.test('workspace responses never disclose connector secrets, payload snapshots or intake hashes',async()=>{reset();const c=await create();config(c.id);const response=await get(c.id);assert.equal(response.status,200);const raw=await response.text();for(const secret of ['provider-secret-test-only','resend-test-only','intake_key_hash','claim_token','test-token'])assert.ok(!raw.includes(secret));assert.equal(response.headers.get('cache-control'),'private, no-store');});
 await t.test('recurring reports generate one previous-month snapshot per workspace',async()=>{reset();await create();assert.equal(await engine.recurringReports(),1);assert.equal(await engine.recurringReports(),0);const r=sqlite.prepare('SELECT * FROM monthly_reports').get();assert.equal(JSON.parse(r.metrics).leads,0);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM monthly_reports').get().n,1);});
 await t.test('runner requires its secret independently of browser identity',async()=>{reset();assert.equal((await runner.POST(new Request('https://orbit.example/api/runner',{method:'POST'}))).status,401);});
});
