import assert from 'node:assert/strict';
import test from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync,readdirSync } from 'node:fs';
import { build } from 'esbuild';

const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
function prepare(query){let values=[];return {bind(...args){values=args;return this},_all(){return {results:sql.prepare(query).all(...values)}},async first(){return sql.prepare(query).get(...values)||null},async all(){return this._all()},async run(){return {meta:{changes:sql.prepare(query).run(...values).changes}}}};}
const db={prepare,async batch(stmts){sql.exec('BEGIN');try{const results=stmts.map(s=>s._all());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
globalThis.__voiceEnv={DB:db,ORBIT_ADMIN_EMAIL:'owner@example.test',ORBIT_RUNNER_TOKEN:'unit-test-runner-token-not-a-real-key'};
globalThis.__voiceHeaders=new Headers();
const built=await build({stdin:{contents:'export * as routes from "./app/api/voice/route.ts";export * as webhook from "./app/api/voice/webhook/[attempt]/route.ts";export * as runner from "./app/api/voice/runner/route.ts";export * as voice from "./lib/voice.ts";export * as shared from "./lib/voice-shared.ts";export * as engine from "./lib/workflow-engine.ts";export * as coach from "./lib/coaching.ts";export * as widget from "./lib/widget.ts";',resolveDir:new URL('..',import.meta.url).pathname},bundle:true,write:false,format:'esm',platform:'node',target:'node24',plugins:[{name:'test-platform',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},args=>({path:args.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},args=>({contents:args.path==='cloudflare:workers'?'export const env=globalThis.__voiceEnv;':args.path==='next/headers'?'export async function headers(){return globalThis.__voiceHeaders;}':'export function redirect(){throw Error("Unexpected redirect")}',loader:'js'}));}}]});
const {routes,webhook,runner,voice,shared,engine,coach,widget}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const auth=(email='owner@example.test',id='owner')=>{globalThis.__voiceHeaders=new Headers({'oai-authenticated-user-id':id,'oai-authenticated-user-email':email});};
const base='https://www.orbitflow.work';
const post=(payload,origin=base)=>routes.POST(new Request(base+'/api/voice',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(payload)}));
const get=(c,extra='')=>routes.GET(new Request(base+'/api/voice'+(c?'?client='+c+extra:'')));
const NOW=Date.UTC(2026,8,19,6,30); // Noon in India.
function reset(){for(const table of ['voice_attempts','voice_calls','voice_settings','voice_suppression','widget_submissions','widget_events','widget_sessions','widget_visitors','widget_sites','coaching_messages','coaching_bookings','coaching_students','coaching_slots','coaching_settings','operation_alerts','workflow_jobs','leads','memberships','workflows','clients','rate_limits'])sql.exec('DELETE FROM '+table);globalThis.__voiceEnv.ORBIT_VOICE_CONNECTORS_JSON='{}';auth();}
function fixture({enabled=true,connected=true,demo=false}={}){
 const c=crypto.randomUUID();sql.prepare("INSERT INTO clients(id,name,intake_key_hash,created_at) VALUES(?,'Example Coaching','not-a-key',?)").run(c,NOW);
 sql.prepare("INSERT INTO memberships(id,client_id,email,user_id,created_at) VALUES(?,?,'member@example.test','member',?)").run(crypto.randomUUID(),c,NOW);
 sql.prepare("INSERT INTO voice_settings(client_id,admin_enabled,client_enabled,test_mode,business_context,role_context,updated_by,updated_at) VALUES(?,?,?,0,'Programming institute with Python and Java courses. Fees need a counsellor.','Follow up on the enquiry and collect the preferred counselling time.','owner',?)").run(c,+enabled,+enabled,NOW);
 if(demo)sql.prepare('INSERT INTO coaching_settings(client_id,is_demo,created_at) VALUES(?,1,?)').run(c,NOW);
 if(connected){const all=JSON.parse(globalThis.__voiceEnv.ORBIT_VOICE_CONNECTORS_JSON);all[c]={apiKey:'test-sarvam-secret-value',orgId:'org-test',workspaceId:'workspace-test',appId:'agent-test',appVersion:2,connectionId:'telephone-test',agentPhoneNumber:'+918000000001',templateReady:true};globalThis.__voiceEnv.ORBIT_VOICE_CONNECTORS_JSON=JSON.stringify(all);}
 return c;
}
async function lead(c,patch={}){return engine.addLead(c,engine.leadInput.parse({externalRef:crypto.randomUUID(),name:'Synthetic Contact',phone:'+447700900001',brief:'Interested in Python; morning classes.',callConsentAt:Date.now()-1000,callConsentEvidence:'Explicit AI-call permission and transcript notice on test form.',...patch}));}
function due(c){sql.prepare("UPDATE voice_calls SET next_at=?,created_at=?,expires_at=? WHERE client_id=?").run(NOW,NOW,NOW+172800000,c);}
function capture(){const payloads=[];return {payloads,transport:async(url,options)=>{payloads.push({url,headers:options.headers,body:JSON.parse(options.body)});return Response.json({attempt_id:'provider-'+payloads.length+'-'+crypto.randomUUID()});}};}
function result(attempt,patch={}){return {attempt_id:attempt.provider_id,status:'connected',channel_info:{channel_type:'v2v',channel_provider:'exotel',agent_phone_number:'+918000000001'},duration:84.5,interaction_id:'interaction-test',final_agent_variables:{outcome:'interested',summary:'Interested in Python, asks for evening counselling.',interest:'Python',callback_request:'Tomorrow evening',next_action:'Counsellor to confirm the time',do_not_call:false},interaction_transcript:[{role:'agent',en_text:"I'm the AI assistant. Is now a good time?"},{role:'user',en_text:'Please arrange a counsellor callback tomorrow evening.'}],...patch};}
function callbackInfo(payload){const u=new URL(payload.body.webhook_config.url);return {id:u.pathname.split('/').at(-1),token:u.searchParams.get('token')};}
const callback=(info,payload)=>webhook.POST(new Request(base+'/api/voice/webhook/'+info.id+'?token='+info.token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),{params:Promise.resolve({attempt:info.id})});

test('AI calling: real routes, SQLite transactions, isolated Sarvam transport',async t=>{
 await t.test('incomplete extraction retains the transcript for review without a redial',async()=>{
  for(const variables of [null,{outcome:'unknown',summary:'',do_not_call:'false'},{outcome:'interested',summary:'Python enquiry.'},{outcome:'interested',summary:' ',do_not_call:false}]){
   reset();const c=fixture();await lead(c);due(c);const mock=capture();await voice.processVoiceCalls(c,mock.transport,NOW);
   const attempt=sql.prepare('SELECT * FROM voice_attempts').get(),info=callbackInfo(mock.payloads[0]),payload=result(attempt,{final_agent_variables:variables});
   assert.equal((await callback(info,payload)).status,200);assert.equal((await callback(info,payload)).status,200);
   const call=sql.prepare('SELECT * FROM voice_calls').get();assert.equal(call.status,'needs_review');assert.equal(call.error_code,'extraction_incomplete');
   const details=await (await get(c,'&call='+call.id)).json();assert.equal(details.detail.attempts[0].transcript.length,2);
   await lead(c);await voice.processVoiceCalls(c,mock.transport,NOW+4*3600000);assert.equal(mock.payloads.length,1);
  }
 });
 await t.test('Sarvam enum outputs are accepted and incomplete notes cannot discard an opt-out',async()=>{
  reset();const c=fixture();await lead(c);due(c);const mock=capture();await voice.processVoiceCalls(c,mock.transport,NOW);
  assert.deepEqual(Object.keys(mock.payloads[0].body.app_config.agent_variables).sort(),['business_context','business_name','enquiry_context','lead_name','preferred_language','role_context']);
  let attempt=sql.prepare('SELECT * FROM voice_attempts').get();await callback(callbackInfo(mock.payloads[0]),result(attempt,{final_agent_variables:{outcome:'interested',summary:'Asked about Python.',do_not_call:'false'}}));
  assert.equal(sql.prepare('SELECT status FROM voice_calls').get().status,'completed');assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_suppression').get().n,0);
  reset();const d=fixture();await lead(d);due(d);const next=capture();await voice.processVoiceCalls(d,next.transport,NOW);attempt=sql.prepare('SELECT * FROM voice_attempts').get();
  await callback(callbackInfo(next.payloads[0]),result(attempt,{final_agent_variables:{outcome:'unknown',summary:'',do_not_call:'true'}}));
  const call=sql.prepare('SELECT status,outcome FROM voice_calls').get();assert.equal(call.status,'needs_review');assert.equal(call.outcome,'do_not_call');assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_suppression').get().n,1);
 });
 await t.test('the shared voice key requires explicit per-client selection and complete setup',async()=>{reset();const c=fixture();const all=JSON.parse(globalThis.__voiceEnv.ORBIT_VOICE_CONNECTORS_JSON);delete all[c].apiKey;globalThis.__voiceEnv.ORBIT_SARVAM_VOICE_KEY='shared-voice-test-secret';globalThis.__voiceEnv.ORBIT_VOICE_CONNECTORS_JSON=JSON.stringify(all);assert.equal((await (await get(c)).json()).connectionReady,false);all[c].useOrbitKey=true;globalThis.__voiceEnv.ORBIT_VOICE_CONNECTORS_JSON=JSON.stringify(all);assert.equal((await (await get(c)).json()).connectionReady,true);await lead(c);due(c);const mock=capture();await voice.processVoiceCalls(c,mock.transport,NOW);assert.equal(mock.payloads[0].headers['X-API-Key'],'shared-voice-test-secret');delete all[c].connectionId;globalThis.__voiceEnv.ORBIT_VOICE_CONNECTORS_JSON=JSON.stringify(all);assert.equal((await (await get(c)).json()).connectionReady,false);delete globalThis.__voiceEnv.ORBIT_SARVAM_VOICE_KEY;});
 await t.test('coaching repeats repair the saved call entry without creating another call',async()=>{reset();const c=fixture({demo:true});sql.prepare('UPDATE voice_settings SET test_mode=1 WHERE client_id=?').run(c);const input=coach.coachingLeadInput.parse({name:'Test Counselling',phone:'+447700900006',course:'python'});const first=await coach.captureLead(c,input);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls WHERE lead_id=?').get(first.id).n,1);sql.prepare('DELETE FROM voice_calls WHERE lead_id=?').run(first.id);await coach.captureLead(c,input);await coach.captureLead(c,input);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls WHERE lead_id=?').get(first.id).n,1);});
 await t.test('busy clients cannot starve another workspace behind their queued leads',async()=>{reset();const a=fixture(),b=fixture();for(let i=0;i<12;i++)await lead(a,{phone:'+447700900'+String(i).padStart(3,'0')});await lead(b,{phone:'+447700901000'});due(a);due(b);sql.prepare('UPDATE voice_calls SET next_at=? WHERE client_id=?').run(NOW-1000,a);const mock=capture();await voice.processVoiceCalls(a,mock.transport,NOW);await voice.processVoiceCalls(undefined,mock.transport,NOW);assert.equal(mock.payloads.length,2);assert.equal(sql.prepare("SELECT COUNT(*) n FROM voice_calls WHERE client_id=? AND status='awaiting_result'").get(b).n,1);});
 await t.test('test capture saves every submitted phone without contacting the provider',async()=>{reset();const c=fixture({demo:true});sql.prepare('DELETE FROM voice_settings WHERE client_id=?').run(c);const cfg=await voice.getVoiceSettings(c);assert.equal(cfg.test_mode,1);assert.equal(cfg.admin_enabled,1);await lead(c,{callConsentAt:null,callConsentEvidence:''});await lead(c,{phone:'+447700900002'});const rows=sql.prepare('SELECT status,error_code FROM voice_calls ORDER BY phone').all();assert.equal(rows.length,2);assert.equal(rows[0].status,'test_saved');assert.equal(rows[0].error_code,'call_consent_required');assert.equal(rows[1].error_code,'test_only');await voice.processVoiceCalls(c,async()=>assert.fail('test capture must never dial'),NOW);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_attempts').get().n,0);});
 await t.test('live activation needs a recent authenticated runner heartbeat',async()=>{reset();const c=fixture();assert.equal((await post({action:'activate',client:c,revision:0,enabled:true})).status,409);await runner.POST(new Request(base+'/api/voice/runner',{method:'POST',headers:{authorization:'Bearer '+globalThis.__voiceEnv.ORBIT_RUNNER_TOKEN}}));assert.equal((await post({action:'activate',client:c,revision:0,enabled:true})).status,200);});
 await t.test('queued work cannot escape a switch back to test mode',async()=>{reset();const c=fixture();await lead(c);due(c);sql.prepare('UPDATE voice_settings SET test_mode=1 WHERE client_id=?').run(c);await voice.processVoiceCalls(c,async()=>assert.fail('test mode'),NOW);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_attempts').get().n,0);});
 await t.test('anonymous, cross-origin and cross-client access is rejected',async()=>{reset();const c=fixture();globalThis.__voiceHeaders=new Headers();assert.equal((await get(c)).status,401);auth('other@example.test','other');assert.equal((await get(c)).status,403);auth();assert.equal((await post({action:'process',client:c},'https://attacker.example')).status,403);});
 await t.test('only admin enables access; members edit only their context and cannot raise limits',async()=>{reset();const c=fixture({enabled:false});auth('member@example.test','member');assert.equal((await post({action:'admin',client:c,revision:0,enabled:true,dailyLimit:100,startHour:10,endHour:18,maxAttempts:2})).status,403);assert.equal((await post({action:'context',client:c,revision:0,businessContext:'Example business facts with sufficient detail.',roleContext:'Qualify the enquiry and collect a callback request.',language:'Hindi'})).status,403);auth();assert.equal((await post({action:'admin',client:c,revision:0,enabled:true,dailyLimit:5,startHour:10,endHour:18,maxAttempts:2})).status,200);auth('member@example.test','member');const p={action:'context',client:c,revision:1,businessContext:'A programming institute with verified course information.',roleContext:'Follow up on enquiries and collect a counselling request.',language:'Hindi'};assert.equal((await post(p)).status,200);assert.equal((await post(p)).status,409);assert.equal((await post({action:'process',client:c})).status,403);});
 await t.test('activation requires provider setup and a real workspace',async()=>{reset();const c=fixture({enabled:false,connected:false});sql.prepare('UPDATE voice_settings SET admin_enabled=1 WHERE client_id=?').run(c);assert.equal((await post({action:'activate',client:c,revision:0,enabled:true})).status,409);const d=fixture({demo:true});assert.equal((await post({action:'activate',client:d,revision:0,enabled:true})).status,409);});
 await t.test('phone, WhatsApp permission or old lead alone never authorizes an AI call',async()=>{reset();const c=fixture();await lead(c,{callConsentAt:null,callConsentEvidence:'',consentAt:Date.now()-1000,consentEvidence:'WhatsApp-only consent on a form.'});assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls').get().n,0);assert.throws(()=>engine.leadInput.parse({name:'Example User',externalRef:'test',phone:'+447700900002',callConsentAt:Date.now()+100000,callConsentEvidence:'AI-call explicit notice.'}));const l=await lead(c,{phone:'+447700900003'});sql.prepare('DELETE FROM voice_calls WHERE lead_id=?').run(l.id);sql.prepare('UPDATE leads SET created_at=? WHERE id=?').run(Date.now()-3*86400000,l.id);assert.equal(await voice.queueVoiceCall(c,l.id),null);});
 await t.test('source retries and repeated forms for one phone create one call; tenants stay separate',async()=>{reset();const a=fixture(),b=fixture();const input=engine.leadInput.parse({externalRef:'same-request',name:'Demo Contact',phone:'+447700900001',callConsentAt:Date.now()-1000,callConsentEvidence:'Explicit AI-call consent at source form.'});await engine.addLead(a,input);await engine.addLead(a,input);await lead(a);await lead(b);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls WHERE client_id=?').get(a).n,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls').get().n,2);});
 await t.test('disabled features, opt-outs and demo workspaces cannot place calls',async()=>{reset();const c=fixture({enabled:false});await lead(c);const d=fixture({demo:true});await lead(d);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls').get().n,0);sql.prepare('UPDATE voice_settings SET admin_enabled=1,client_enabled=1 WHERE client_id=?').run(c);const l=await lead(c,{phone:'+447700900002'});due(c);sql.prepare('UPDATE leads SET opted_out_at=? WHERE id=?').run(NOW,l.id);await voice.processVoiceCalls(c,async()=>assert.fail('must not dial'),NOW);assert.equal(sql.prepare('SELECT status FROM voice_calls').get().status,'cancelled');});
 await t.test('India calling hours respect opening and closing boundaries',async()=>{const start=Date.UTC(2026,8,19,4,30),end=Date.UTC(2026,8,19,12,30);assert.equal(shared.nextCallTime(start-1,10,18),start);assert.equal(shared.nextCallTime(start,10,18),start);assert.equal(shared.nextCallTime(end,10,18),start+86400000);reset();const c=fixture();await lead(c);due(c);await voice.processVoiceCalls(c,async()=>assert.fail('after hours'),end);assert.equal(sql.prepare('SELECT next_at FROM voice_calls').get().next_at,start+86400000);});
 await t.test('concurrent runners send once, include tenant context, and keep credentials out of database/API',async()=>{reset();const c=fixture();await lead(c);due(c);const mock=capture();await Promise.all([voice.processVoiceCalls(c,mock.transport,NOW),voice.processVoiceCalls(c,mock.transport,NOW)]);assert.equal(mock.payloads.length,1);const p=mock.payloads[0];assert.equal(p.headers['X-API-Key'],'test-sarvam-secret-value');assert.equal(p.body.app_config.agent_variables.business_name,'Example Coaching');assert.equal(p.body.app_config.app_overrides.initial_language_name,'Hindi');assert.equal(p.body.user_config.user_phone_number,'+447700900001');assert.match(p.body.app_config.app_overrides.initial_bot_message,/AI/);const a=sql.prepare('SELECT * FROM voice_attempts').get();assert.equal(a.status,'awaiting_result');const raw=JSON.stringify(a);assert.ok(!raw.includes(callbackInfo(p).token));assert.ok(!raw.includes('test-sarvam-secret-value'));const api=await (await get(c)).text();for(const value of ['test-sarvam-secret-value','token_hash','context_snapshot','org-test'])assert.ok(!api.includes(value));});
 await t.test('one active call per client and daily cap apply across concurrent runs',async()=>{reset();const c=fixture();sql.prepare('UPDATE voice_settings SET daily_limit=1 WHERE client_id=?').run(c);await lead(c);await lead(c,{phone:'+447700900002'});due(c);const mock=capture();await voice.processVoiceCalls(c,mock.transport,NOW);assert.equal(mock.payloads.length,1);const a=sql.prepare('SELECT * FROM voice_attempts').get();await callback(callbackInfo(mock.payloads[0]),result(a));await voice.processVoiceCalls(c,mock.transport,NOW+60000);assert.equal(mock.payloads.length,1);});
 await t.test('timeout or 5xx needs review and is never blindly retried',async()=>{reset();const c=fixture();await lead(c);due(c);let sends=0;await voice.processVoiceCalls(c,async()=>{sends++;throw Error('timeout after acceptance');},NOW);assert.equal(sql.prepare('SELECT status FROM voice_calls').get().status,'needs_review');await voice.processVoiceCalls(c,async()=>{sends++;return Response.json({attempt_id:'wrong'});},NOW+600000);assert.equal(sends,1);});
 await t.test('authenticated results store transcript and structured response without claiming a booking',async()=>{reset();const c=fixture();await lead(c);due(c);const mock=capture();await voice.processVoiceCalls(c,mock.transport,NOW);const a=sql.prepare('SELECT * FROM voice_attempts').get(),info=callbackInfo(mock.payloads[0]),payload=result(a);assert.equal((await callback({...info,token:'0'.repeat(72)},payload)).status,401);assert.equal((await callback(info,{...payload,attempt_id:'foreign-attempt'})).status,409);assert.equal((await callback(info,payload)).status,200);assert.equal((await callback(info,payload)).status,200);assert.equal((await callback(info,{...payload,status:'failed'})).status,409);const v=sql.prepare('SELECT * FROM voice_calls').get();assert.equal(v.status,'completed');assert.equal(v.outcome,'interested');assert.equal(JSON.parse(v.answers).callback_request,'Tomorrow evening');assert.equal(sql.prepare('SELECT COUNT(*) n FROM coaching_bookings').get().n,0);auth('member@example.test','member');const details=await (await get(c,'&call='+v.id)).json();assert.equal(details.detail.attempts[0].transcript.length,2);assert.equal(details.detail.attempts[0].duration,84.5);});
 await t.test('completion arriving before outbound response does not regress to awaiting result',async()=>{reset();const c=fixture();await lead(c);due(c);await voice.processVoiceCalls(c,async(url,options)=>{const p={body:JSON.parse(options.body)},a=sql.prepare('SELECT * FROM voice_attempts').get();assert.equal((await callback(callbackInfo(p),result({...a,provider_id:'fast-response'}))).status,200);return Response.json({attempt_id:'fast-response'});},NOW);assert.equal(sql.prepare('SELECT status FROM voice_calls').get().status,'completed');});
 await t.test('no-answer retries once after four hours; failed provider calls do not retry',async()=>{reset();const c=fixture();await lead(c);due(c);const mock=capture();await voice.processVoiceCalls(c,mock.transport,NOW);let a=sql.prepare('SELECT * FROM voice_attempts').get(),i=callbackInfo(mock.payloads[0]);await voice.acceptVoiceResult(i.id,i.token,result(a,{status:'no_answer',duration:null,interaction_transcript:null,final_agent_variables:null}),NOW);let row=sql.prepare('SELECT * FROM voice_calls').get();assert.equal(row.status,'queued');assert.equal(row.next_at,NOW+4*3600000);await voice.processVoiceCalls(c,mock.transport,row.next_at);assert.equal(mock.payloads.length,2);a=sql.prepare('SELECT * FROM voice_attempts ORDER BY attempt_number DESC').get();i=callbackInfo(mock.payloads[1]);await voice.acceptVoiceResult(i.id,i.token,result(a,{status:'no_answer',final_agent_variables:null}),NOW+4*3600000);assert.equal(sql.prepare('SELECT status FROM voice_calls').get().status,'no_answer');});
 await t.test('do-not-call is durable across repeated leads and isolated to that client',async()=>{reset();const c=fixture(),d=fixture();await lead(c);due(c);const mock=capture();await voice.processVoiceCalls(c,mock.transport,NOW);const a=sql.prepare('SELECT * FROM voice_attempts').get(),i=callbackInfo(mock.payloads[0]);const p=result(a,{final_agent_variables:{outcome:'do_not_call',do_not_call:true,summary:'Asked not to be called.'}});await voice.acceptVoiceResult(i.id,i.token,p,NOW);await voice.acceptVoiceResult(i.id,i.token,p,NOW);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_suppression').get().n,1);await lead(c);await lead(d);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls WHERE client_id=?').get(d).n,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls WHERE client_id=?').get(c).n,1);});
 await t.test('pause cancels pending calls and start cannot revive them',async()=>{reset();const c=fixture();await lead(c);due(c);auth('member@example.test','member');assert.equal((await post({action:'activate',client:c,revision:0,enabled:false})).status,200);assert.equal(sql.prepare('SELECT status FROM voice_calls').get().status,'cancelled');await voice.processVoiceCalls(c,async()=>assert.fail('paused'),NOW);});
 await t.test('widget permission is separate from analytics and WhatsApp and routes to correct client',async()=>{reset();const c=fixture(),site=crypto.randomUUID(),origin='https://coaching.example';sql.prepare("INSERT INTO widget_sites(id,client_id,name,origins,privacy_url,courses,created_at,updated_at) VALUES(?,?,'Example Coaching',?,'https://coaching.example/privacy',?, ?, ?)").run(site,c,JSON.stringify([origin]),JSON.stringify([{id:'python',label:'Python'}]),NOW,NOW);const request=(callConsent,phone)=>new Request(base+'/api/widget/'+site,{method:'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':'203.0.113.8'},body:JSON.stringify({action:'lead',requestId:crypto.randomUUID(),name:'Demo Student',phone,course:'python',contactConsent:true,whatsappConsent:false,callConsent,version:'orbit-widget-2026-09-v1',startedAt:Date.now()-5000,website:''})});globalThis.__voiceEnv.ORBIT_RATE_LIMIT_SALT='test-rate-limit-secret-that-is-long-enough';let response=await widget.handleWidget(request(false,'+447700900011'),site);assert.equal(response.status,201,await response.clone().text());assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls').get().n,0);response=await widget.handleWidget(request(true,'+447700900012'),site);assert.equal(response.status,201,await response.clone().text());assert.equal(sql.prepare('SELECT COUNT(*) n FROM voice_calls').get().n,1);const record=sql.prepare('SELECT * FROM leads WHERE phone=?').get('+447700900012');assert.ok(record.call_consent_at);assert.equal(record.consent_at,null);});
 await t.test('expired conversation details are hidden before cleanup and removal preserves suppression',async()=>{reset();const c=fixture();await lead(c);due(c);const mock=capture();await voice.processVoiceCalls(c,mock.transport,NOW);const a=sql.prepare('SELECT * FROM voice_attempts').get(),i=callbackInfo(mock.payloads[0]);await voice.acceptVoiceResult(i.id,i.token,result(a),NOW);const old=Date.now()-91*86400000;sql.prepare('UPDATE voice_attempts SET started_at=?').run(old);sql.prepare('UPDATE voice_calls SET updated_at=?').run(old);const id=sql.prepare('SELECT id FROM voice_calls').get().id,j=await (await get(c,'&call='+id)).json();assert.equal(j.detail.summary,null);assert.equal(j.detail.attempts[0].transcript,null);await voice.purgeVoiceTranscripts();assert.equal(sql.prepare('SELECT transcript FROM voice_attempts').get().transcript,null);});
 await t.test('dedicated runner is protected independently of signed-in browser identity',async()=>{reset();assert.equal((await runner.POST(new Request(base+'/api/voice/runner',{method:'POST'}))).status,401);const r=await runner.POST(new Request(base+'/api/voice/runner',{method:'POST',headers:{authorization:'Bearer '+globalThis.__voiceEnv.ORBIT_RUNNER_TOKEN}}));assert.equal(r.status,200);assert.ok(sql.prepare("SELECT expires_at FROM rate_limits WHERE key='voice-runner-heartbeat'").get().expires_at>Date.now());});
});
