import assert from 'node:assert/strict';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {build} from 'esbuild';

const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
function prepare(query){let values=[];return{bind(...v){values=v;return this},async first(){return sql.prepare(query).get(...values)||null},async all(){return{results:sql.prepare(query).all(...values),success:true}},async run(){return{meta:{changes:sql.prepare(query).run(...values).changes},success:true}}}}
const db={prepare,async batch(rows){sql.exec('BEGIN');try{const out=[];for(const row of rows)out.push(await row.all());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.__widgetEnv={DB:db,ORBIT_RATE_LIMIT_SALT:'test-salt-32-characters-not-production',ORBIT_ADMIN_EMAIL:'owner@gmail.com'};
globalThis.__widgetHeaders=new Headers();
const result=await build({stdin:{contents:'export * as widget from "./lib/widget.ts";export * as tracking from "./app/api/tracking/route.ts";export * as shared from "./lib/widget-shared.ts";export * as google from "./lib/google-auth.ts";export * as paths from "./lib/auth-paths.ts";export * as access from "./lib/operations-access.ts";',resolveDir:new URL('..',import.meta.url).pathname},bundle:true,write:false,format:'esm',platform:'node',target:'node24',plugins:[{name:'test-platform',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},a=>({path:a.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.__widgetEnv;':a.path==='next/headers'?'export async function headers(){return globalThis.__widgetHeaders}':'export function redirect(){throw Error("Unexpected redirect")}',loader:'js'}))}}]});
const {widget,tracking,shared,google,paths,access}=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
const origin='https://coaching.example',api='https://www.orbitflow.work',admin='https://admin.orbitflow.work';
function seed(){const client=crypto.randomUUID(),site=crypto.randomUUID(),now=Date.now();sql.prepare('INSERT INTO clients(id,name,intake_key_hash,created_at) VALUES(?,?,?,?)').run(client,'Coaching','none',now);sql.prepare('INSERT INTO coaching_settings(client_id,is_demo,created_at) VALUES(?,1,?)').run(client,now);sql.prepare('INSERT INTO widget_sites(id,client_id,name,origins,privacy_url,courses,color,enabled,retention_days,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,30,?,?)').run(site,client,'Coaching widget',JSON.stringify([origin]),origin+'/privacy',JSON.stringify(shared.defaultWidgetCourses),'#fa783c',now,now);return{client,site};}
const post=(site,data,o=origin)=>widget.handleWidget(new Request(api+'/api/widget/'+site,{method:'POST',headers:{origin:o,'content-type':'application/json'},body:JSON.stringify(data)}),site);
const consent=(key=crypto.randomUUID())=>({action:'consent',analytics:true,version:shared.WIDGET_CONSENT_VERSION,visitorKey:key,sessionId:crypto.randomUUID(),attribution:{source:'demo',campaign:'summer',referrer:'google.com'},device:'desktop'});
const event=(more={})=>({id:crypto.randomUUID(),type:'page_view',path:'/courses/mern?email=hidden@example.test',at:Date.now(),properties:{},...more});
const enquiry=(more={})=>({action:'lead',requestId:crypto.randomUUID(),name:'Demo Student',phone:'9876543210',email:'',course:'mern',contactConsent:true,whatsappConsent:false,version:shared.WIDGET_CONSENT_VERSION,startedAt:Date.now()-5000,website:'',...more});
const login=(email='owner@gmail.com',id='owner')=>globalThis.__widgetHeaders=new Headers({'oai-authenticated-user-email':email,'oai-authenticated-user-id':id});
const report=(site,query='')=>tracking.GET(new Request(admin+'/api/tracking?site='+site+query));

test('widget captures only consented activity and isolates each coaching site',async t=>{
 await t.test('public configuration never allows a foreign origin and events need consent',async()=>{const {site}=seed();assert.equal((await post(site,consent(),'https://evil.example')).status,403);assert.equal((await post(site,{action:'events',token:'fake',events:[event()]})).status,401);assert.equal((await post(site,{...consent(),analytics:false})).status,400);assert.equal(sql.prepare('SELECT COUNT(*) n FROM widget_events').get().n,0);});
 await t.test('events deduplicate, redact URL data and reject unapproved event properties',async()=>{const {site}=seed(),c=consent(),r=await post(site,c);assert.equal(r.status,200);const {token}=await r.json(),e=event();const payload={action:'events',token,events:[e]};assert.equal((await post(site,payload)).status,200);assert.equal((await (await post(site,payload)).json()).accepted,0);const saved=sql.prepare('SELECT * FROM widget_events WHERE site_id=?').get(site);assert.equal(saved.path,'/courses/mern');assert.equal((await post(site,{...payload,events:[event({properties:{email:'secret@test.com'}})]})).status,400);assert.equal((await post(site,{...payload,events:[event({path:'/account/details'})]})).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM widget_events WHERE site_id=?').get(site).n,1);const b=seed();assert.equal((await post(b.site,payload)).status,401);});
 await t.test('phone-only enquiry works without analytics; retry creates one lead and no outgoing messages',async()=>{const {site,client}=seed(),e=enquiry();assert.equal((await post(site,{...e,contactConsent:false})).status,400);assert.equal((await post(site,e)).status,201);assert.equal((await post(site,e)).status,200);assert.equal((await post(site,{...e,name:'Changed'})).status,409);assert.equal(sql.prepare('SELECT COUNT(*) n FROM leads WHERE client_id=?').get(client).n,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM coaching_messages WHERE client_id=?').get(client).n,0);assert.equal(sql.prepare('SELECT visitor_id FROM widget_submissions WHERE site_id=?').get(site).visitor_id,null);});
 await t.test('withdrawal deletes history, unlinks the enquiry and rejects queued/replayed sessions',async()=>{const {site}=seed(),c=consent(),{token}=await (await post(site,c)).json();await post(site,{action:'events',token,events:[event()]});await post(site,enquiry({token}));assert.ok(sql.prepare('SELECT visitor_id FROM widget_submissions WHERE site_id=?').get(site).visitor_id);assert.equal((await post(site,{action:'revoke',visitorKey:c.visitorKey})).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM widget_events WHERE site_id=?').get(site).n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM widget_sessions WHERE site_id=?').get(site).n,0);assert.equal(sql.prepare('SELECT visitor_id FROM widget_submissions WHERE site_id=?').get(site).visitor_id,null);assert.equal((await post(site,c)).status,409);assert.equal((await post(site,{action:'events',token,events:[event()]})).status,401);assert.equal((await post(site,consent())).status,200);});
 await t.test('reports and exports require membership; exports omit contacts and expired events',async()=>{const {site,client}=seed(),{token}=await (await post(site,consent())).json();await post(site,{action:'events',token,events:[event()]});await post(site,enquiry({token}));globalThis.__widgetHeaders=new Headers();assert.equal((await report(site)).status,401);login('outsider@gmail.com','outsider');assert.equal((await report(site)).status,403);sql.prepare('INSERT INTO memberships(id,client_id,email,created_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),client,'member@gmail.com',Date.now());login('member@gmail.com','member');const res=await report(site,'&export=events');assert.equal(res.status,200);const data=await res.json();assert.equal(data.events.length,1);assert.ok(!JSON.stringify(data).includes('9876543210'));assert.ok(!JSON.stringify(data).includes('Demo Student'));sql.prepare('UPDATE widget_events SET expires_at=0 WHERE site_id=?').run(site);assert.equal((await (await report(site,'&export=events')).json()).events.length,0);await widget.purgeExpiredWidgetData(site);assert.equal(sql.prepare('SELECT COUNT(*) n FROM widget_events WHERE site_id=?').get(site).n,0);});
});

const rsa=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk={...await crypto.subtle.exportKey('jwk',rsa.publicKey),kid:'test-key',use:'sig'};
const clientId='test.apps.googleusercontent.com';
const b64=v=>Buffer.from(v).toString('base64url');
async function jwt(nonce,more={}){const now=Math.floor(Date.now()/1000),body={iss:'https://accounts.google.com',sub:'12345678',aud:clientId,iat:now,exp:now+3600,nonce,email:'owner@gmail.com',email_verified:true,name:'Owner',...more},unsigned=b64(JSON.stringify({alg:'RS256',kid:'test-key'}))+'.'+b64(JSON.stringify(body));return unsigned+'.'+b64(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',rsa.privateKey,new TextEncoder().encode(unsigned)));}
const certs=async()=>Response.json({keys:[jwk]});
function configure(){globalThis.__widgetEnv.ORBIT_GOOGLE_CLIENT_ID=clientId;globalThis.__widgetEnv.ORBIT_GOOGLE_CLIENT_SECRET='local-test-only';}

test('Google sign-in binds identity, browser, origin and authorization separately',async t=>{
 await t.test('a missing provider is unavailable and redirect targets cannot escape the site',async()=>{assert.equal((await google.startGoogle(new Request(admin+'/api/auth/google/start'))).headers.get('location'),'/login?error=google-unavailable');for(const v of ['//evil.test','/\\evil.test','https://evil.test','/api/auth/google/start','/login'])assert.equal(paths.safeReturnPath(v),'/');assert.equal(paths.safeReturnPath('/tracking?days=7'),'/tracking?days=7');});
 await t.test('signed claims require correct issuer, audience, nonce, freshness and verified email',async()=>{configure();assert.equal((await google.verifyGoogleIdToken(await jwt('nonce'),'nonce',clientId,certs)).id,'google:12345678');for(const changes of [{iss:'evil'},{aud:'another-app'},{nonce:'wrong'},{exp:0},{email_verified:false},{email:'owner@unmanaged.test'}])await assert.rejects(google.verifyGoogleIdToken(await jwt('nonce',changes),'nonce',clientId,certs));const token=await jwt('nonce');await assert.rejects(google.verifyGoogleIdToken(token.slice(0,-8)+'invalid!','nonce',clientId,certs));});
 await t.test('a full exchange uses PKCE, single-use browser state and a host-only session',async()=>{const r=await google.startGoogle(new Request(admin+'/api/auth/google/start?return_to=%2Ftracking')),url=new URL(r.headers.get('location')),flowCookie=r.headers.getSetCookie()[0].split(';')[0];assert.equal(url.hostname,'accounts.google.com');assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('scope'),'openid email profile');const state=url.searchParams.get('state'),nonce=url.searchParams.get('nonce');let exchanges=0;const fetcher=async(u,o)=>{if(u.includes('/certs'))return certs();exchanges++;assert.ok(o.body.get('code_verifier'));assert.equal(o.body.get('redirect_uri'),admin+'/api/auth/google/callback');return Response.json({id_token:await jwt(nonce)});};const callback=cookie=>new Request(admin+'/api/auth/google/callback?state='+state+'&code=test-code',{headers:{cookie}});
 assert.match((await google.finishGoogle(callback(''),fetcher)).headers.get('location'),/error/);assert.equal(exchanges,0);
 const done=await google.finishGoogle(callback(flowCookie),fetcher);assert.equal(done.headers.get('location'),'/tracking');const setCookie=done.headers.getSetCookie().find(s=>s.startsWith('__Host-orbitflow_session='));assert.match(setCookie,/HttpOnly; Secure; SameSite=Lax/);assert.ok(!setCookie.includes('Domain='));const session=setCookie.split(';')[0];assert.equal((await google.googleUser(new Headers({cookie:session,'x-orbit-site-host':'admin.orbitflow.work'}))).email,'owner@gmail.com');assert.equal(await google.googleUser(new Headers({cookie:session,'x-orbit-site-host':'app.orbitflow.work'})),null);assert.match((await google.finishGoogle(callback(flowCookie),fetcher)).headers.get('location'),/error/);assert.equal(exchanges,1);
 globalThis.__widgetHeaders=new Headers({cookie:session,'x-orbit-site-host':'admin.orbitflow.work'});assert.equal((await access.ownerAccess()).owner,true);
 assert.equal((await google.signOutGoogle(new Request(admin+'/api/auth/signout',{method:'POST',headers:{cookie:session,origin:'https://evil.test'}}))).status,403);assert.equal((await google.signOutGoogle(new Request(admin+'/api/auth/signout',{method:'POST',headers:{cookie:session,origin:admin}}))).status,303);assert.equal(await google.googleUser(new Headers({cookie:session,'x-orbit-site-host':'admin.orbitflow.work'})),null);
 });
});
