"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { ArrowUpRight, Bell, Check, Clock3, FileDown, LoaderCircle, Plus, RefreshCw, Settings2, Workflow } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Progress } from "@/components/ui/progress";
import WorkspaceNav from "@/components/workspace-nav";
import type { SiteNavigation } from "@/lib/site-domains";
import { leadStatuses, onboardingItems, requestCategories, workflowTemplates, type Lead } from "@/lib/operations-shared";

type Client={id:string;name:string;active:number};
type Metrics={month:string;leads:number;won:number;responded:number;average_response_minutes:number|null;usage:{action:string;accepted:number}[]};
type Case={id:string;title:string;body:string;content_hash:string;status:string;approved_at:number|null};
type Job={id:string;action:string;status:string;attempts:number;error_code:string|null;next_at:number;provider_id:string|null};
type Directory={owner:boolean;clients:Client[];demand:{category:string;clients:number;requests:number}[];error?:string};
type MutationResult={error?:string;ok?:boolean;intakeKey:string;clientId:string};
type Data={client:Client;owner:boolean;leads:Lead[];page:number;hasMore:boolean;totals:{total:number;new:number;won:number;overdue:number;responded:number;average_response_minutes:number|null};jobs:Job[];alerts:{id:string;code:string;job_id:string}[];workflows:{template:string;enabled:number}[];onboarding:{item:string;completed:number}[];cases:Case[];reports:{month:string;metrics:Metrics;generated_at:number}[];requests:{category:string;description:string;created_at:number}[];members:{id:string;email:string;active:number;claimed:number}[];connections:{crm:boolean;email:boolean;whatsapp:boolean};monthMetrics:Metrics};
const dt=(n:number|null)=>n?new Date(n).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"Not recorded";
const minutes=(n:number|null)=>n===null?"—":n<60?`${Math.round(n)} min`:`${(n/60).toFixed(1)} hr`;
const human=(s:string)=>s.replaceAll("_"," ").replaceAll("."," · ");
function Badge({children,kind=""}:{children:ReactNode;kind?:string}){return <span className={`op-badge ${kind}`}>{children}</span>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="op-field"><span>{label}</span>{children}</label>}
function Blank({title,children}:{title:string;children:ReactNode}){return <Empty className="op-empty"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{children}</EmptyDescription></EmptyHeader></Empty>}
function Stat({label,value,note}:{label:string;value:ReactNode;note?:string}){return <div className="op-stat"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function downloadReport(metrics:Metrics){const blob=new Blob([JSON.stringify(metrics,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`orbit-report-${metrics.month}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function Portal({navigation}:{navigation:SiteNavigation}){
 const [clients,setClients]=useState<Client[]>([]),[owner,setOwner]=useState(false),[selected,setSelected]=useState(""),[data,setData]=useState<Data|null>(null),[page,setPage]=useState(0),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[tab,setTab]=useState("leads"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[modal,setModal]=useState<"client"|"lead"|"settings"|"case"|null>(null),[lead,setLead]=useState<Lead|null>(null),[study,setStudy]=useState<Case|null>(null),[intakeKey,setIntakeKey]=useState(""),[callConsent,setCallConsent]=useState(false),[consent,setConsent]=useState(false),[responseRecorded,setResponseRecorded]=useState(false),[optOut,setOptOut]=useState(false),[leadStatus,setLeadStatus]=useState("new"),[category,setCategory]=useState<string>(requestCategories[0]),[sendConfirmed,setSendConfirmed]=useState(false),[caseConfirmed,setCaseConfirmed]=useState(false),[reviewJob,setReviewJob]=useState<Job|null>(null);
 const sequence=useRef(0),requestId=useRef("");
 const load=useCallback(async()=>{
  const seq=++sequence.current;setLoading(true);
  try{
   const res=await fetch(`/api/operations${selected?`?client=${selected}&month=${month}&page=${page}`:""}`,{cache:"no-store"});const json=await res.json() as Data & Directory;
   if(!res.ok)throw new Error(json.error||"Unable to load workspace.");if(sequence.current!==seq)return;
   if(selected){setData(json);setOwner(json.owner);}else{setClients(json.clients);setOwner(json.owner);setDemand(json.demand);if(json.clients[0])setSelected(json.clients[0].id);else setData(null);}
  }catch(e){if(sequence.current===seq){setData(null);setError(e instanceof Error?e.message:"Unable to load workspace.");}}
  finally{if(sequence.current===seq)setLoading(false);}
 },[selected,month,page]);
 const [demand,setDemand]=useState<{category:string;clients:number;requests:number}[]>([]);
 useEffect(()=>{void load();return()=>{sequence.current++;}},[load]);
 async function refreshList(){const res=await fetch("/api/operations",{cache:"no-store"});const json=await res.json() as Directory;if(!res.ok)throw new Error(json.error);setClients(json.clients);setDemand(json.demand);}
 async function act(payload:Record<string,unknown>,success="Saved."){
  if(busy)return null;setBusy(true);setError("");setNotice("");
  try{const res=await fetch("/api/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...(selected?{client:selected}:{}),...payload}),signal:AbortSignal.timeout(70000)});const json=await res.json() as MutationResult;if(!res.ok)throw new Error(json.error||"Unable to save.");setNotice(success);await load();return json;}
  catch(e){setError(e instanceof Error?e.message:"Unable to save. Please try again.");return null;}
  finally{setBusy(false);}
 }
 function openLead(item:Lead|null){setLead(item);setConsent(false);setCallConsent(false);setResponseRecorded(false);setOptOut(false);setSendConfirmed(false);setLeadStatus(item?.status||"new");requestId.current=crypto.randomUUID();setModal("lead");}
 function openCase(item:Case|null){setStudy(item);setCaseConfirmed(false);requestId.current=crypto.randomUUID();setModal("case");}
 async function submitClient(e:FormEvent<HTMLFormElement>){
  e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError("");
  try{const res=await fetch("/api/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createClient",requestId:requestId.current,name:f.get("name"),email:f.get("email")})});const json=await res.json() as MutationResult;if(!res.ok)throw new Error(json.error);await refreshList();setSelected(json.clientId);setIntakeKey(json.intakeKey);setModal("settings");setNotice("Workspace created. Share its portal link with the client after Site access is configured.");}
  catch(e){setError(e instanceof Error?e.message:"Unable to create workspace.");}finally{setBusy(false);}
 }
 async function submitLead(e:FormEvent<HTMLFormElement>){
  e.preventDefault();const f=new FormData(e.currentTarget);
  const res=lead?await act({action:"updateLead",id:lead.id,status:leadStatus,followUpAt:f.get("followUp")?new Date(String(f.get("followUp"))).getTime():null,responded:responseRecorded,optOut}):await act({action:"addLead",lead:{externalRef:requestId.current,name:f.get("name"),email:f.get("email"),phone:f.get("phone"),brief:f.get("brief"),consentEvidence:consent?f.get("evidence"):"",consentAt:consent?new Date(String(f.get("consentAt"))).getTime():null,callConsentAt:callConsent?new Date(String(f.get("callConsentAt"))).getTime():null,callConsentEvidence:callConsent?f.get("callEvidence"):""}},"Lead captured.");
  if(res)setModal(null);
 }
 const selectedName=clients.find(c=>c.id===selected)?.name;
 const checklistDone=data?.onboarding.filter(i=>i.completed).length||0;
 return <main className="op-page shell">
  <WorkspaceNav active="operations" owner={owner} websiteHref={navigation.websiteHref} portalHref={navigation.portalHref} studioHref={navigation.studioHref}/>
  <div className="op-title"><div><span className="eyebrow orange">CLIENT OPERATIONS</span><h1>Client operations.</h1><p>Leads, follow-ups and results in one workspace.</p></div>{owner&&<button className="button button-primary" disabled={busy} onClick={()=>{requestId.current=crypto.randomUUID();setModal("client")}}><Plus size={18}/>New workspace</button>}</div>
  {error&&<div role="alert" className="op-error">{error}<button onClick={()=>{setError("");void load()}}>Try again</button></div>}
  {notice&&<p className="op-notice" role="status"><Check size={17}/>{notice}</p>}
  {clients.length>0&&<div className="op-workspace-bar"><Select value={selected} disabled={busy} onValueChange={value=>{setData(null);setSelected(value);setPage(0);setIntakeKey("");setNotice("");setError("")}}><SelectTrigger aria-label="Client workspace"><SelectValue placeholder="Select workspace"/></SelectTrigger><SelectContent>{clients.map(c=><SelectItem value={c.id} key={c.id}>{c.name}</SelectItem>)}</SelectContent></Select><Badge>{owner?"Studio owner":"Client member"}</Badge><div className="op-bar-actions"><button className="button button-outline" disabled={loading||busy} onClick={()=>{setError("");void load()}}><RefreshCw size={16}/>Refresh</button>{owner&&<button className="button button-outline" onClick={()=>setModal("settings")}><Settings2 size={16}/>Access & setup</button>}</div></div>}
  {loading&&!data?<div className="op-loading"><Skeleton className="h-28 w-full"/><Skeleton className="h-72 w-full"/></div>:!data?<Blank title={clients.length?"Select a workspace":"Your workspace starts here."}>{owner?"Create a client workspace, add its client contact and agree the first workflow.":"Ask the studio owner to grant access to your sign-in email."}</Blank>:<>
   <div className="op-stats"><Stat label="All leads" value={data.totals.total}/><Stat label="New enquiries" value={data.totals.new}/><Stat label="Follow-ups due" value={data.totals.overdue}/><Stat label="Won" value={data.totals.won}/><Stat label="First human response" value={minutes(data.totals.average_response_minutes)} note={`Average · ${data.totals.responded} recorded`}/></div>
   <Tabs value={tab} onValueChange={setTab} className="op-tabs"><TabsList aria-label="Client operations"><TabsTrigger value="leads">Leads</TabsTrigger><TabsTrigger value="workflows">Workflows {data.alerts.length>0&&<Badge kind="warn">{data.alerts.length}</Badge>}</TabsTrigger><TabsTrigger value="reports">Reports</TabsTrigger><TabsTrigger value="onboarding">Onboarding</TabsTrigger><TabsTrigger value="cases">Case studies</TabsTrigger><TabsTrigger value="requests">Product requests</TabsTrigger></TabsList>
   <TabsContent value="leads"><section className="op-panel"><div className="op-section-head"><div><h2>Lead pipeline</h2><p>{selectedName} · track the next action for every lead.</p></div><button className="button button-primary" onClick={()=>openLead(null)}><Plus size={17}/>Add lead</button></div>{!data.leads.length?<Blank title="No leads yet">Add a lead or connect your website through the secure intake endpoint.</Blank>:<div className="op-table"><Table><TableHeader><TableRow><TableHead>Contact</TableHead><TableHead>Status</TableHead><TableHead>Next follow-up</TableHead><TableHead>First response</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{data.leads.map(l=><TableRow key={l.id}><TableCell><strong>{l.name}</strong><span>{l.email}</span></TableCell><TableCell><Badge kind={l.status==="won"?"good":""}>{l.status}</Badge></TableCell><TableCell>{l.follow_up_at?<span className={l.follow_up_at<Date.now()&&!['won','lost'].includes(l.status)?"orange":""}>{dt(l.follow_up_at)}</span>:"Not scheduled"}</TableCell><TableCell>{l.first_response_at?minutes((l.first_response_at-l.created_at)/60000):"Awaiting response"}</TableCell><TableCell><button className="text-button" onClick={()=>openLead(l)}>Open brief <ArrowUpRight size={17}/></button></TableCell></TableRow>)}</TableBody></Table></div>}<div className="op-pagination"><button className="button button-outline" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button className="button button-outline" disabled={!data.hasMore||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div></section></TabsContent>
   <TabsContent value="workflows"><div className="op-section-head"><div><h2>Repeat the useful work.</h2><p>Enable a template for new leads. Review exceptions here.</p></div>{owner&&<button className="button button-primary" disabled={busy} onClick={()=>act({action:"run"},"Due workflow runs processed.")}><Workflow size={17}/>{busy?"Processing…":"Process due runs"}</button>}</div><div className="op-workflow-grid">{workflowTemplates.map(t=><article className="op-panel" key={t.key}><Workflow className="orange"/><h3>{t.name}</h3><p>{t.description}</p><Badge kind={(t.key==="crm.sync"?data.connections.crm:data.connections.email)?"good":"warn"}>{(t.key==="crm.sync"?data.connections.crm:data.connections.email)?"Configured · verify with a test":"Not connected"}</Badge><label className="op-check"><Checkbox disabled={!owner||busy} checked={!!data.workflows.find(w=>w.template===t.key)?.enabled} onCheckedChange={v=>act({action:"workflow",template:t.key,enabled:v===true})}/><span>Run for new leads</span></label></article>)}<article className="op-panel"><Clock3 className="orange"/><h3>WhatsApp first follow-up</h3><p>Queue one approved template from a lead brief after checking recorded opt-in.</p><Badge kind={data.connections.whatsapp?"good":"warn"}>{data.connections.whatsapp?"Configured · verify with a test":"Not connected"}</Badge><p className="op-note">Provider acceptance is tracked. Confirm delivery in Meta; delivery receipts are not connected yet.</p></article></div>
    <section className="op-panel"><h3><Bell size={18}/>Needs attention</h3>{data.alerts.length?data.alerts.map(a=><div className="op-alert-row" key={a.id}><div><strong>{human(a.code)}</strong><span>Review the related run below before retrying.</span></div><button className="button button-outline" disabled={busy} onClick={()=>act({action:"ackAlert",id:a.id})}>Acknowledge</button></div>):<p>No open alerts.</p>}</section>
    <section className="op-panel"><h3>Recent runs</h3>{!data.jobs.length?<Blank title="No workflow runs yet">Enable a workflow and add a lead, or queue an opted-in WhatsApp follow-up.</Blank>:<div className="op-table"><Table><TableHeader><TableRow><TableHead>Workflow</TableHead><TableHead>State</TableHead><TableHead>Attempts</TableHead><TableHead>Details</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{data.jobs.map(j=><TableRow key={j.id}><TableCell>{human(j.action)}</TableCell><TableCell><Badge kind={j.status==="succeeded"?"good":["failed","needs_review","blocked"].includes(j.status)?"warn":""}>{j.status==="succeeded"?"Provider accepted":human(j.status)}</Badge></TableCell><TableCell>{j.attempts} / 5</TableCell><TableCell>{j.error_code?human(j.error_code):j.status==="retry"?dt(j.next_at):"—"}</TableCell><TableCell>{owner&&["blocked","failed","retry"].includes(j.status)&&j.attempts<5?<button className="text-button" disabled={busy} onClick={()=>act({action:"retryJob",id:j.id},"Retry queued. Process due runs to continue.")}>Queue retry</button>:owner&&j.status==="needs_review"?<button className="text-button" onClick={()=>setReviewJob(j)}>Verify with provider</button>:"—"}</TableCell></TableRow>)}</TableBody></Table></div>}<p className="op-note">Scheduled retries require a connected runner. “Process due runs” processes up to five runs now. Pausing a template stops new runs; existing queued runs remain.</p></section>
   </TabsContent>
   <TabsContent value="reports"><section className="op-panel"><div className="op-section-head"><div><h2>Monthly results</h2><p>Lead outcomes and provider usage, with no estimated revenue.</p></div><Field label="Reporting month (UTC)"><Input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></Field></div><div className="op-stats report-stats"><Stat label="Leads received" value={data.monthMetrics.leads}/><Stat label="Won in this cohort" value={data.monthMetrics.won}/><Stat label="Human responses" value={data.monthMetrics.responded}/><Stat label="Average response" value={minutes(data.monthMetrics.average_response_minutes)}/></div><h3>Provider usage</h3>{data.monthMetrics.usage.length?<div className="op-usage">{data.monthMetrics.usage.map(u=><div key={u.action}><span>{human(u.action)}</span><strong>{u.accepted} accepted</strong></div>)}</div>:<p>No successful provider runs recorded this month.</p>}<p className="op-note">Response time starts when OrbitFlow receives the lead and ends when a teammate records their first human response. Automated messages do not count. Won status reflects the current outcome of this month’s lead cohort.</p><button className="button button-primary" disabled={busy} onClick={()=>act({action:"report",month},"Monthly snapshot saved.")}><FileDown size={17}/>Save monthly snapshot</button></section><section className="op-panel"><h3>Saved reports</h3>{data.reports.length?data.reports.map(r=><div className="op-alert-row" key={r.month}><div><strong>{r.month}</strong><span>{r.metrics.leads} leads · {r.metrics.won} won · saved {dt(r.generated_at)}</span></div><button className="button button-outline" onClick={()=>downloadReport(r.metrics)}><FileDown size={16}/>Download</button></div>):<p>Save a snapshot or connect the monthly reporting runner.</p>}</section></TabsContent>
   <TabsContent value="onboarding"><section className="op-panel"><div className="op-section-head"><div><h2>A shared launch checklist.</h2><p>Agree the workflow, test it and make ownership clear.</p></div><Badge>{checklistDone} / {onboardingItems.length} complete</Badge></div><Progress value={checklistDone/onboardingItems.length*100} aria-label="Onboarding completion"/>{onboardingItems.map(i=><label className="op-check checklist-item" key={i.key}><Checkbox disabled={busy} checked={!!data.onboarding.find(c=>c.item===i.key)?.completed} onCheckedChange={v=>act({action:"onboarding",item:i.key,completed:v===true})}/><span>{i.label}</span></label>)}<p className="op-note">Checklist completion records your team’s confirmation. It does not automatically verify a provider connection.</p></section></TabsContent>
   <TabsContent value="cases"><div className="op-section-head"><div><h2>Proof, with permission.</h2><p>Record a real result and let the client review the exact wording.</p></div>{owner&&<button className="button button-primary" onClick={()=>openCase(null)}><Plus size={17}/>Draft case study</button>}</div>{data.cases.length?data.cases.map(c=><article className="op-panel" key={c.id}><Badge kind={c.status==="approved"?"good":""}>{c.status}</Badge><h3>{c.title}</h3><p className="op-case-excerpt">{c.body}</p><button className="button button-outline" onClick={()=>openCase(c)}>{owner?"Edit draft":"Review & permission"}</button>{c.approved_at&&<p className="op-note">Permission recorded {dt(c.approved_at)}. No case study is published automatically.</p>}</article>):<Blank title="Your first real result belongs here">After a pilot, capture the starting point, measured outcome, timeframe and limitations. The client approves the exact draft before it can be shared.</Blank>}</TabsContent>
   <TabsContent value="requests"><div className="op-two-col"><section className="op-panel"><h2>What should OrbitFlow do next?</h2><p>Describe a recurring problem and how often it happens.</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await act({action:"request",category,description:f.get("description")},"Product request recorded.")){form.reset();if(owner)await refreshList();}}}><Field label="Area"><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{requestCategories.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></Field><Field label="Problem and desired outcome"><Textarea name="description" minLength={15} maxLength={2000} required rows={4}/></Field><button className="button button-primary" disabled={busy}>Save request</button></form></section><section className="op-panel"><h3>Subscription product direction</h3><p>Compare repeated requests across clients before choosing the subscription scope.</p>{owner&&demand.length?<div className="op-usage">{demand.map(d=><div key={d.category}><span>{d.category}</span><strong>{d.clients} clients · {d.requests} requests</strong></div>)}</div>:<p className="op-note">Client requests will provide the evidence for the next product decision.</p>}<p className="op-note">Billing is deferred until a repeatable offer, agreed pricing and payment provider are selected.</p></section></div><section className="op-panel"><h3>Workspace requests</h3>{data.requests.length?data.requests.map((r,i)=><div className="op-request" key={i}><Badge>{r.category}</Badge><p>{r.description}</p><small>{dt(r.created_at)}</small></div>):<p>No product requests recorded yet.</p>}</section></TabsContent>
   </Tabs>
  </>}
  <Dialog open={modal!==null} onOpenChange={v=>{if(!v&&!busy){setModal(null);setIntakeKey("")}}}><DialogContent className="op-dialog"><DialogHeader><DialogTitle>{modal==="client"?"Create a client workspace":modal==="settings"?"Access & setup":modal==="case"?owner?"Case-study draft":"Review this case study":lead?lead.name:"Add a lead"}</DialogTitle><DialogDescription>{modal==="client"?"Grant access to the client’s sign-in email.":modal==="settings"?"Manage client members and your website’s secure intake.":modal==="case"?"Only the client can approve the exact wording for publication.":lead?"Record the next action and actual human response.":"Capture the contact details and the work they need help with."}</DialogDescription></DialogHeader>
  {error&&<p className="op-error" role="alert">{error}</p>}
  {modal==="client"&&<form onSubmit={submitClient}><Field label="Business name"><Input name="name" required minLength={2} maxLength={160}/></Field><Field label="Client sign-in email"><Input name="email" type="email" required maxLength={254}/></Field><p className="op-note">This grants application membership. Site sharing must also allow the client to open OrbitFlow. No invitation email is sent automatically.</p><button className="button button-primary" disabled={busy}>Create workspace</button></form>}
  {modal==="lead"&&<form onSubmit={submitLead} key={lead?.id||requestId.current}>{lead?<>
    <p>{lead.email}{lead.phone&&` · ${lead.phone}`}</p><p className="op-brief">{lead.brief||"No project brief supplied."}</p><Field label="Lead status"><Select value={leadStatus} onValueChange={setLeadStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{leadStatuses.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></Field><Field label="Next follow-up (your local time)"><Input type="datetime-local" name="followUp" defaultValue={lead.follow_up_at?new Date(lead.follow_up_at-new Date(lead.follow_up_at).getTimezoneOffset()*60000).toISOString().slice(0,16):""}/></Field>
    <label className="op-check"><Checkbox checked={responseRecorded} disabled={!!lead.first_response_at} onCheckedChange={v=>setResponseRecorded(v===true)}/><span>{lead.first_response_at?`First response recorded ${dt(lead.first_response_at)}`:"I have just sent the first human response"}</span></label><a className="button button-outline" href={`mailto:${lead.email}`}>Open email app <ArrowUpRight size={16}/></a><p className="op-note">Opening email does not send a message or record a response.</p><label className="op-check"><Checkbox checked={!!lead.opted_out_at||optOut} disabled={!!lead.opted_out_at} onCheckedChange={v=>setOptOut(v===true)}/><span>Contact has opted out of WhatsApp</span></label><button className="button button-primary" disabled={busy}>Save lead changes</button>
    {owner&&<div className="op-send"><h3>WhatsApp follow-up</h3><p className="op-note">{lead.consent_at?`Opt-in recorded ${dt(lead.consent_at)}: ${lead.consent_evidence}`:"No WhatsApp opt-in is recorded."}</p><label className="op-check"><Checkbox checked={sendConfirmed} onCheckedChange={v=>setSendConfirmed(v===true)}/><span>I checked the opt-in and want to queue the configured approved template.</span></label><button type="button" className="button button-outline" disabled={busy||!sendConfirmed||!lead.consent_at||optOut||!!lead.opted_out_at||!data?.connections.whatsapp} onClick={()=>act({action:"sendWhatsApp",id:lead.id,confirm:true},"WhatsApp template queued. Process due runs to send.")}>Queue WhatsApp template</button></div>}
   </>:<><div className="op-two-col"><Field label="Full name"><Input name="name" required minLength={2} maxLength={100}/></Field><Field label="Email (optional with phone)"><Input name="email" type="email" maxLength={254}/></Field></div><Field label="Phone (optional, international format)"><Input name="phone" placeholder="+919876543210" maxLength={16}/></Field><Field label="Project brief"><Textarea name="brief" rows={3} maxLength={3000}/></Field><label className="op-check"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>I have evidence of this contact’s opt-in for WhatsApp communication from this business.</span></label>{consent&&<><Field label="Consent received at (local time)"><Input name="consentAt" type="datetime-local" required/></Field><Field label="Consent source / evidence reference"><Textarea name="evidence" required minLength={10} maxLength={1000} placeholder="For example: form submission reference and the exact consent wording shown."/></Field></>}<label className="op-check"><Checkbox checked={callConsent} onCheckedChange={v=>setCallConsent(v===true)}/><span>I have explicit permission for an AI-assisted follow-up call and stored call notes.</span></label>{callConsent&&<><Field label="AI-call consent received at"><Input name="callConsentAt" type="datetime-local" required/></Field><Field label="AI-call permission source and exact wording"><Textarea name="callEvidence" required minLength={15} maxLength={1500}/></Field></>}<button className="button button-primary" disabled={busy}>Save lead</button></>}</form>}
  {modal==="settings"&&owner&&<><h3>Client members</h3>{data?.members.map(m=><div className="op-member" key={m.id}><div><strong>{m.email}</strong><small>{m.active?m.claimed?"Active":"Awaiting first sign-in":"Revoked"}</small></div>{m.active===1&&<button className="text-button" disabled={busy} onClick={()=>act({action:"revokeMember",id:m.id},"Member access revoked.")}>Revoke</button>}</div>)}<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await act({action:"addMember",email:f.get("email")},"Member access granted. Share the portal link after configuring Site access."))form.reset();}}><Field label="Grant access to sign-in email"><Input name="email" type="email" required/></Field><button className="button button-outline" disabled={busy}>Grant access</button></form><div className="op-divider"/><h3>Website intake</h3><p className="op-note">Use a server-side integration to capture leads in this workspace. Keep its key private.</p><code className="op-code">/api/intake/{selected}</code>{intakeKey?<><p className="op-note">Copy this key now. It will not be shown again.</p><textarea aria-label="New intake key" className="op-secret" readOnly value={intakeKey}/></>:<button className="button button-outline" disabled={busy} onClick={async()=>{const r=await act({action:"rotateKey"},"Intake key rotated. Update your website’s server integration.");if(r)setIntakeKey(r.intakeKey)}}>Rotate intake key</button>}<p className="op-note">Rotating the key immediately revokes the previous key. Provider credentials and the recurring runner are configured by the studio operator on the server.</p></>}
  {modal==="case"&&(owner?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await act({action:"caseDraft",id:study?.id||requestId.current,title:f.get("title"),text:f.get("text"),expectedHash:study?.content_hash||null},"Draft saved. Client permission is required for this version."))setModal(null);}} key={study?.id||requestId.current}><Field label="Title"><Input name="title" required minLength={3} maxLength={160} defaultValue={study?.title||""}/></Field><Field label="Exact proposed publication copy"><Textarea name="text" required minLength={30} maxLength={8000} rows={10} defaultValue={study?.body||""} placeholder="Describe the starting problem, actual measured results, dates, method and limitations. Include the exact business name or attribution you intend to publish."/></Field><p className="op-note">Saving any edit resets approval. Use real customer evidence; this draft stays private.</p><button className="button button-primary" disabled={busy}>Save draft for review</button></form>:study&&<><h3>{study.title}</h3><p className="op-brief">{study.body}</p><Badge>{study.status}</Badge><label className="op-check"><Checkbox checked={caseConfirmed} onCheckedChange={v=>setCaseConfirmed(v===true)}/><span>I am authorized to approve this exact case-study wording, including its attribution, for OrbitFlow’s public website and marketing.</span></label><button className="button button-primary" disabled={!caseConfirmed||busy} onClick={async()=>{if(await act({action:"caseConsent",id:study.id,hash:study.content_hash,decision:"approve",confirm:true},"Permission recorded for this exact draft. Nothing was published automatically."))setModal(null);}}>Approve this version</button><button className="button button-outline" disabled={busy} onClick={async()=>{if(await act({action:"caseConsent",id:study.id,hash:study.content_hash,decision:"revoke",confirm:true},"Publication permission revoked."))setModal(null)}}>Revoke permission</button></>)}
  </DialogContent></Dialog>
  <Dialog open={!!reviewJob} onOpenChange={v=>{if(!v&&!busy)setReviewJob(null)}}><DialogContent className="op-dialog"><DialogHeader><DialogTitle>Verify the provider result</DialogTitle><DialogDescription>Check the provider’s logs first. This records an already accepted send; it does not send another message.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await act({action:"resolveJob",id:reviewJob?.id,providerId:f.get("providerId"),confirm:true},"Provider acceptance recorded after manual verification."))setReviewJob(null)}}><Field label="Verified provider message ID"><Input name="providerId" required minLength={3} maxLength={250}/></Field><p className="op-note">If the provider did not accept it, leave it in review. Do not mark it accepted.</p><button className="button button-primary" disabled={busy}>Record verified acceptance</button></form></DialogContent></Dialog>
  {busy&&<div className="op-saving" role="status"><LoaderCircle className="spin" size={18}/>Saving changes…</div>}
 </main>;
}
